# auto generated from sync-defs.py
archi_data = {
    "loc": {
        "Level 2 Reached": 1,
        "Level 3 Reached": 2,
        "Level 4 Reached": 3,
        "Level 5 Reached": 4,
        "Level 6 Reached": 5,
        "Level 7 Reached": 6,
        "Level 8 Reached": 7,
        "Level 9 Reached": 8,
        "Level 10 Reached": 9,
        "Level 11 Reached": 10,
        "Level 12 Reached": 11,
        "Level 13 Reached": 12,
        "Level 14 Reached": 13,
        "Level 15 Reached": 14,
        "Level 16 Reached": 15,
        "Level 17 Reached": 16,
        "Level 18 Reached": 17,
        "Level 19 Reached": 18,
        "Level 20 Reached": 19,
        "Level 21 Reached": 20,
        "Level 22 Reached": 21,
        "Level 23 Reached": 22,
        "Level 24 Reached": 23,
        "Level 25 Reached": 24,
        "Level 26 Reached": 25,
        "Level 27 Reached": 26,
        "Level 28 Reached": 27,
        "Level 29 Reached": 28,
        "Level 30 Reached": 29,
        "Enemy: Flame Knuckle": 30,
        "Enemy: That Asshole": 31,
        "Enemy: Red": 32,
        "Enemy: Belly": 33,
        "Enemy: Red & Belly": 34,
        "Enemy: Bruce": 35,
        "Enemy: Opha Superior": 36,
        "Enemy: The Sentinel": 37,
        "Enemy: The Empyrean Sentinel": 38,
        "Enemy: The Invincible Sentinel": 39,
        "Enemy: The Invincible Empyrean Sentinel": 40,
        "Enemy: Colonel T. Zarpedon": 41,
        "Enemy: Tungsteena Zarpedon, Ascended": 42,
        "Enemy: Corporal Bob": 43,
        "Enemy: Meg": 44,
        "Enemy: Dean": 45,
        "Enemy: Lost Legion Courier": 46,
        "Enemy: Lost Legion Powersuit Noob": 47,
        "Enemy: Surrendering Dahl Soldier": 48,
        "Enemy: Raum-Kampfjet Mark V": 49,
        "Enemy: Rabid Adams": 50,
        "Enemy: Drongo Bones": 51,
        "Enemy: Boomer": 52,
        "Enemy: Tony Slows": 53,
        "Enemy: Poop Deck": 54,
        "Enemy: Bosun": 55,
        "Enemy: Deadlift": 56,
        "Enemy: Squat": 57,
        "Enemy: X-STLK-23": 58,
        "Enemy: Mini Destroyer": 59,
        "Enemy: Son of Flamey": 60,
        "Enemy: Grandson of Flamey": 61,
        "Enemy: Antagonized Kraggon": 62,
        "Enemy: Iwajira": 63,
        "Enemy: Even-More-Disgusting Tork": 64,
        "Enemy: Swagman": 65,
        "Enemy: Rooster Booster": 66,
        "Enemy: Felicity Rampant": 67,
        "Enemy: Magma Rivers": 68,
        "Enemy: Wally Wrong": 69,
        "Enemy: Fair Dinkum": 70,
        "Enemy: Giant Shuggurath of Ice": 71,
        "Enemy: Lunestalker Sr.": 72,
        "Enemy: Maureen": 73,
        "Enemy: Meat Head": 74,
        "Enemy: Oscar": 75,
        "Enemy: Eghood": 76,
        "Enemy: CL4P-L3K": 77,
        "Enemy: Master Poacher": 78,
        "Enemy: Dan Zando": 79,
        "Enemy: Nel": 80,
        "Enemy: Scavenger Beast": 81,
        "Enemy: Scav Beast Rider": 82,
        "Enemy: Lil' Scavenger Beast": 83,
        "Enemy: Lil' Scav": 84,
        "Enemy: Powersuit Felicity": 85,
        "Enemy: Defense Destroyer": 86,
        "Enemy: Lost Legion Eternal Powersuit": 87,
        "Enemy: Guardian Pondor": 88,
        "Enemy: Eclipse": 89,
        "Enemy: EOS": 90,
        "Enemy: Despair": 91,
        "Enemy: Self-Loathing": 92,
        "Enemy: The Sponx": 93,
        "Enemy: SH4D0W-TP": 94,
        "Enemy: Self-Esteem": 95,
        "Enemy: Hope": 96,
        "Enemy: Denial Subroutine": 97,
        "Enemy: 5UP4-3G0-TP": 98,
        "Enemy: Minion": 99,
        "Enemy: Teh Earworm": 100,
        "Enemy: MINAC Minion": 101,
        "Enemy: D1GN1TY-TP": 102,
        "Enemy: Shame": 103,
        "Enemy: Chip": 104,
        "Enemy: Cookie": 105,
        "Vending PandoraSimulation Firestone : Guns": 106,
        "Vending PandoraSimulation Firestone : Meds": 107,
        "Vending PandoraSimulation Firestone : Ammo": 108,
        "Vending OverlookSimulation Recall Handler Gamma: Guns": 109,
        "Vending OverlookSimulation Recall Handler Gamma: Meds": 110,
        "Vending OverlookSimulation Recall Handler Gamma: Ammo": 111,
        "Vending OverlookSimulation Gyrus Groove: Ammo": 112,
        "Vending OverlookSimulation Gyrus Groove: Meds": 113,
        "Vending TrainingFacility: Ammo": 114,
        "Vending TrainingFacility: Meds": 115,
        "Vending TrainingFacility: Guns": 116,
        "Vending Concordia Nina: Meds": 117,
        "Vending Concordia Nina: Ammo": 118,
        "Vending Concordia Earl: Meds": 119,
        "Vending Concordia Earl: Guns": 120,
        "Vending Concordia Grinder: Ammo": 121,
        "Vending Concordia Moxxi's: Ammo": 122,
        "Vending Concordia Moxxi's: Guns": 123,
        "Vending CrisisScar RedBelly Arena: Ammo": 124,
        "Vending CrisisScar RedBelly Arena: Meds": 125,
        "Vending CrisisScar RedBelly Arena: Guns": 126,
        "Vending Deck13 FastTravel: Guns": 127,
        "Vending Deck13 FastTravel: Ammo": 128,
        "Vending Deck13 FastTravel: Meds": 129,
        "Vending Deck13 TestingRange: Ammo": 130,
        "Vending Deck13 TestingRange: Guns": 131,
        "Vending FakeDeck13: Meds": 132,
        "Vending FakeDeck13: Ammo": 133,
        "Vending FakeDeck13: Guns": 134,
        "Vending Eleseer: Ammo": 135,
        "Vending Eleseer: Meds": 136,
        "Vending Eleseer: Guns": 137,
        "Vending EyeOfHelios: Ammo": 138,
        "Vending EyeOfHelios: Meds": 139,
        "Vending EyeOfHelios: Guns": 140,
        "Vending Intro CommandCenter: Ammo": 141,
        "Vending Intro Moonshot: Ammo": 142,
        "Vending Intro Moonshot: Meds": 143,
        "Vending HubOfHeroism Helios Immigration Station: Ammo": 144,
        "Vending HubOfHeroism Helios Immigration Station: Meds": 145,
        "Vending HubOfHeroism Central Terminal: Ammo": 146,
        "Vending HubOfHeroism Central Terminal: Meds": 147,
        "Vending HubOfHeroism Central Terminal: Guns": 148,
        "Vending LunarLaunchingStation Start: Ammo": 149,
        "Vending LunarLaunchingStation Start: Meds": 150,
        "Vending LunarLaunchingStation Start: Guns": 151,
        "Vending LunarLaunchingStation Hub: Ammo": 152,
        "Vending LunarLaunchingStation Hub: Meds": 153,
        "Vending LunarLaunchingStation Eye Entrance: Ammo": 154,
        "Vending LunarLaunchingStation Eye Entrance: Meds": 155,
        "Vending Motherlessboard Entrance: Guns": 156,
        "Vending Motherlessboard Entrance: Meds": 157,
        "Vending Motherlessboard Entrance: Ammo": 158,
        "Vending Motherlessboard Memory Bank 2: Meds": 159,
        "Vending Motherlessboard Memory Bank 2: Ammo": 160,
        "Vending Motherlessboard Memory Bank 2: Guns": 161,
        "Vending Motherlessboard Memory Bank 4: Meds": 162,
        "Vending Motherlessboard Memory Bank 4: Ammo": 163,
        "Vending Motherlessboard Memory Bank 4: Guns": 164,
        "Vending OutfallPumpingStation Start: Ammo": 165,
        "Vending OutfallPumpingStation Start: Meds": 166,
        "Vending OutfallPumpingStation Start: Guns": 167,
        "Vending OutlandsCanyon Start: Ammo": 168,
        "Vending OutlandsCanyon Start: Meds": 169,
        "Vending OutlandsCanyon Start: Guns": 170,
        "Vending OutlandsCanyon Fingersmith Halls: Ammo": 171,
        "Vending OutlandsCanyon Fingersmith Halls: Meds": 172,
        "Vending OutlandsCanyon Fingersmith Halls: Guns": 173,
        "Vending OutlandsSpur Start: Ammo": 174,
        "Vending OutlandsSpur Start: Meds": 175,
        "Vending OutlandsSpur Processing Plant: Ammo": 176,
        "Vending OutlandsSpur Processing Plant: Meds": 177,
        "Vending OutlandsSpur Pumping Station: Ammo": 178,
        "Vending OutlandsSpur Pumping Station: Meds": 179,
        "Vending PitysFall Start: Ammo": 180,
        "Vending PitysFall Start: Meds": 181,
        "Vending PitysFall Start: Guns": 182,
        "Vending PitysFall Drakensburg Gangway: Ammo": 183,
        "Vending PitysFall Drakensburg Gangway: Meds": 184,
        "Vending PitysFall Drakensburg Gangway: Guns": 185,
        "Vending PitysFall Starboard Ascent: Ammo": 186,
        "Vending PitysFall Engine Room: Ammo": 187,
        "Vending PitysFall Engine Room: Meds": 188,
        "Vending PitysFall Command Center: Ammo": 189,
        "Vending PitysFall Command Center: Meds": 190,
        "Vending RegolithRange Start: Ammo": 191,
        "Vending RegolithRange Start: Meds": 192,
        "Vending RegolithRange Waystation: Ammo": 193,
        "Vending RegolithRange Waystation: Meds": 194,
        "Vending RnD Start: Ammo": 195,
        "Vending RnD Start: Meds": 196,
        "Vending SerenitysWaste Janey: Ammo": 197,
        "Vending SerenitysWaste Janey: Meds": 198,
        "Vending Subconscious The Subconscious: Meds": 199,
        "Vending Subconscious The Subconscious: Ammo": 200,
        "Vending Subconscious Insertion Shard: Meds": 201,
        "Vending Subconscious Insertion Shard:  Guns": 202,
        "Vending subconscious Insertion Shard:  Ammo": 203,
        "Vending Subconscious Terrorhead Gorge:  Ammo": 204,
        "Vending Subconscious Terrorhead Gorge:  Meds": 205,
        "Vending Subconscious Sub-Subconscious: Meds": 206,
        "Vending Subconscious Sub-Subconscious: Guns": 207,
        "Vending Subconscious Sub-Subconscious: Ammo": 208,
        "Vending Subconscious Subliminal Plaza Entrance: Meds": 209,
        "Vending Subconscious Subliminal Plaza Entrance: Ammo": 210,
        "Vending Subconscious Subliminal Plaza: Meds": 211,
        "Vending Cortex Terminal Dendrite: Ammo": 212,
        "Vending Cortex Terminal Dendrite: Meds": 213,
        "Vending Cortex Terminal Dendrite: Guns": 214,
        "Vending Cortex The Cortex: Meds": 215,
        "Vending Cortex The Cortex: Guns": 216,
        "Vending Cortex The Cortex: Ammo": 217,
        "Vending The MeriffsOffice: Ammo": 218,
        "Vending The MeriffsOffice: Meds": 219,
        "Vending Nexus Positive Terminal: Guns": 220,
        "Vending Nexus Positive Terminal: Meds": 221,
        "Vending Nexus SYS_ADMIN: Ammo": 222,
        "Vending Nexus SYS_ADMIN: Meds": 223,
        "Vending Nexus Positive Terminal: Ammo": 224,
        "Vending Nexus SYS_ADMIN: Guns": 225,
        "Vending TitanIndustrialFacility Start: Ammo": 226,
        "Vending TitanIndustrialFacility Start: Meds": 227,
        "Vending TitanIndustrialFacility Start: Guns": 228,
        "Vending TitanIndustrialFacility Nexus: Ammo": 229,
        "Vending TitanIndustrialFacility Nexus: Meds": 230,
        "Vending TitanIndustrialFacility Production Plant Entrance: Ammo": 231,
        "Vending TitanRobotPlant Start: Ammo": 232,
        "Vending TitanRobotPlant Start: Meds": 233,
        "Vending TitanRobotPlant Start: Guns": 234,
        "Vending TitanRobotPlant Power Control: Guns": 235,
        "Vending TitanRobotPlant Unit Embarkation: Ammo": 236,
        "Vending TitanRobotPlant Unit Embarkation: Meds": 237,
        "Vending TitanRobotPlant Unit Embarkation: Guns": 238,
        "Vending TritonFlats Diemens Crater: Ammo": 239,
        "Vending TritonFlats Diemens Crater: Meds": 240,
        "Vending TritonFlats Diemens Crater: Guns": 241,
        "Vending TritonFlats Banjo Point: Ammo": 242,
        "Vending TritonFlats Banjo Point: Meds": 243,
        "Vending TritonFlats The Pale: Ammo": 244,
        "Vending TritonFlats Lunar Junction: Meds": 245,
        "Vending TritonFlats Lunar Junction: Guns": 246,
        "Vending TritonFlats Darksiders: Meds": 247,
        "Vending TritonFlats Darksiders: Guns": 248,
        "Vending TritonFlats Flinder's Needle: Ammo": 249,
        "Vending TritonFlats Flinder's Needle: Meds": 250,
        "Vending TychosRibs: Ammo": 251,
        "Vending TychosRibs: Meds": 252,
        "Vending VeinsOfHelios Start: Ammo": 253,
        "Vending VeinsOfHelios Start: Meds": 254,
        "Vending VeinsOfHelios Start: Guns": 255,
        "Vending VoragoSolitude Start: Ammo": 256,
        "Vending VoragoSolitude Start: Meds": 257,
        "Vending VoragoSolitude Start: Guns": 258,
        "Vending Holodome Start: Meds": 259,
        "Vending Holodome Start: Guns": 260,
        "Vending Holodome Arena: Ammo": 261,
        "Vending Holodome Arena: Meds": 262,
        "Vending Holodome Start: Ammo": 263,
        "Vending Holodome Arena: Guns": 264,
        "Generic: Kraggon": 265,
        "Generic: Scav": 266,
        "Generic: Lunatic": 267,
        "Generic: Lil' Midget": 268,
        "Generic: Antagonized Kraggon": 269,
        "Generic: Tork": 270,
        "Generic: Not-So-Cute Tork": 271,
        "Generic: Volatile Tork Swarming": 272,
        "Generic: Tork Swarming": 273,
        "Generic: Scav SAM Turret": 274,
        "Generic: Freezing Rathyd": 275,
        "Generic: Shuggurath of Ice": 276,
        "Generic: Lil' Darksider": 277,
        "Generic: Madman": 278,
        "Generic: Lil' Madman": 279,
        "Generic: Darksider": 280,
        "Generic: Scav Laser Turret": 281,
        "Generic: Borrowed Laser Turret": 282,
        "Generic: Raider": 283,
        "Generic: Outlaw": 284,
        "Generic: lil' Lunatic": 285,
        "Generic: Lil' Outlaw": 286,
        "Generic: Stolen Dhal Jetfighter": 287,
        "Generic: Badass scav": 288,
        "Generic: Rathyd": 289,
        "Generic: Stinging Rathyd": 290,
        "Generic: Shuggurath": 291,
        "Generic: Laser Moon Buggy": 292,
        "Generic: Energized shuggurath": 293,
        "Generic: Dhal SAM Turret": 294,
        "Generic: Bosuns' Shield Regenerator": 295,
        "Generic: Badass Lil' Scav": 296,
        "Generic: Badass": 297,
        "Challenge Elemental: Chemical Burn": 298,
        "Challenge Elemental: Frost Bite": 299,
        "Challenge Elemental: Watt's Up?": 300,
        "Challenge Elemental: Way of the Enkindling": 301,
        "Challenge Elemental: Some Like It Hot": 302,
        "Challenge Elemental: Toxic Takedown": 303,
        "Challenge Elemental: Out with a Bang": 304,
        "Challenge Melee: Martial Marshal": 305,
        "Challenge Melee: Captain Cutty": 306,
        "Challenge Assault Rifle: Aim to Please": 307,
        "Challenge Assault Rifle: Assault With a Deadly Weapon": 308,
        "Challenge Assault Rifle: Hot Lead Injection": 309,
        "Challenge Assault Rifle: Crouch Potato": 310,
        "Challenge Assault Rifle: Assaulty Dog": 311,
        "Challenge Laser: Aggressive Lasik": 312,
        "Challenge Laser: Light 'em Up": 313,
        "Challenge Laser: Battle Star": 314,
        "Challenge Laser: Pew Pew": 315,
        "Challenge Laser: I See the Light": 316,
        "Challenge Rocket Launcher: Get a Rocket up Ya": 317,
        "Challenge Rocket Launcher: Collateral Damage": 318,
        "Challenge Rocket Launcher: Punker Buster": 319,
        "Challenge Rocket Launcher: Hand of God": 320,
        "Challenge Rocket Launcher: Missile Magnet": 321,
        "Challenge Rocket Launcher: Magic Missile": 322,
        "Challenge Pistol: Pistoleer": 323,
        "Challenge Pistol: Trigger Happy": 324,
        "Challenge Pistol: Magnum Maestro": 325,
        "Challenge Pistol: Gunslinger": 326,
        "Challenge Pistol: Pistol Whipped": 327,
        "Challenge Shotgun: Hello Uncle Buckshot": 328,
        "Challenge Shotgun: Boomstick Boogie": 329,
        "Challenge Shotgun: Shotty Workmanship": 330,
        "Challenge Shotgun: Over Achiever": 331,
        "Challenge Shotgun: Shotgunning the Breeze": 332,
        "Challenge SMG: Take It All!": 333,
        "Challenge SMG: Bring the Pain": 334,
        "Challenge SMG: Nice Spray Job": 335,
        "Challenge SMG: And Stay Down!": 336,
        "Challenge SMG: Dinky Death Dealer": 337,
        "Challenge Sniper: Melon Splitter": 338,
        "Challenge Sniper: Sharp Shooter": 339,
        "Challenge Sniper: Ol' Skool": 340,
        "Challenge Sniper: Penetrating Wound": 341,
        "Challenge Sniper: Clean and Simple": 342,
        "Challenge Sniper: Critical Reception": 343,
        "Challenge Sniper: Windage Adjustment": 344,
        "Challenge Recovery: Soup's Up!": 345,
        "Challenge Recovery: Rollin' the Ice": 346,
        "Challenge Recovery: Had a Bit of a Shocker": 347,
        "Challenge Recovery: The Phoenix": 348,
        "Challenge Recovery: Up Unt at Zem": 349,
        "Challenge Recovery: Doctor Feels Good": 350,
        "Challenge Recovery: Better You Than Me": 351,
        "Challenge Recovery: There Can Be Only... Me": 352,
        "Challenge Shields: Ammo Eater": 353,
        "Challenge Shields: Amplitude Killulation": 354,
        "Challenge Shields: Nova Say Die": 355,
        "Challenge Shields: Wet Work": 356,
        "Challenge Shields: That'll Learn Ya": 357,
        "Challenge Vehicles: Shut Up and Drive": 358,
        "Challenge Vehicles: Splat 'n' Slide": 359,
        "Challenge Vehicles: Fender Bender": 360,
        "Challenge Vehicles: Improvise, Adapt, Overcome": 361,
        "Challenge Vehicles: Road Warrior": 362,
        "Challenge Vehicles: Pancakes for Breakfast": 363,
        "Challenge Economy: Over the Moon": 364,
        "Challenge Economy: Mom Would Be Proud": 365,
        "Challenge Economy: Impulse Shopper": 366,
        "Challenge Economy: Pawn Broker": 367,
        "Challenge Economy: Mr. Money Pits": 368,
        "Challenge Economy: Trade Negotiations": 369,
        "Challenge Enemies: Kiss My Badass": 370,
        "Challenge Enemies: Crash & Burn": 371,
        "Challenge Enemies: Get Some!": 372,
        "Challenge Enemies: No Suit for You!": 373,
        "Challenge Enemies: More Where That Came From": 374,
        "Challenge Enemies: Not So Tough Now": 375,
        "Challenge Enemies: Dose of Death": 376,
        "Challenge Enemies: Slayer of Titans": 377,
        "Challenge Enemies: Big Game Hunt": 378,
        "Challenge Enemies: Gift That Keeps Giving": 379,
        "Challenge Enemies: Exterminator": 380,
        "Challenge Enemies: The One That Says B.A.M.F.": 381,
        "Challenge Enemies: It Wasn't Yours, Anyway": 382,
        "Challenge Enemies: Die, Moon Jerks": 383,
        "Challenge Enemies: Space Dead": 384,
        "Challenge Enemies: That Was Unpleasant": 385,
        "Challenge Enemies: Torkin' Out the Trash": 386,
        "Challenge Enemies: Pest Control": 387,
        "Challenge General: The Duelist": 388,
        "Challenge General: Barrel of Laughs": 389,
        "Challenge General: Having Trouble Breathing?": 390,
        "Challenge General: Projectile Proliferation": 391,
        "Challenge General: Last Gasp": 392,
        "Challenge General: Day of the Dead": 393,
        "Challenge General: Dark Sider": 394,
        "Challenge General: Executioner": 395,
        "Challenge General: Action Hero": 396,
        "Challenge General: Comet Crash": 397,
        "Challenge General: Ice to Meet You": 398,
        "Challenge General: One Man's Trash": 399,
        "Challenge General: Throw Me the Money!": 400,
        "Challenge Grenade: Home Nade Cookin'": 401,
        "Challenge Grenade: Sprayowee": 402,
        "Challenge Grenade: Betty Boom": 403,
        "Challenge Grenade: Big MIRV": 404,
        "Challenge Grenade: See Ya on the Other Side": 405,
        "Challenge Grenade: Pass the Chianti": 406,
        "Challenge Grinder: Master Chef": 407,
        "Challenge Grinder: Greater Than the Sum of its Parts": 408,
        "Challenge Grinder: This Time for Sure": 409,
        "Challenge Grinder: The Daily Grind": 410,
        "Challenge Loot: Aaaaaand OPEN!": 411,
        "Challenge Loot: Scrounging Around": 412,
        "Challenge Loot: One for Every Occasion": 413,
        "Challenge Loot: Rare as Rocking Horse...": 414,
        "Challenge Loot: A Chunk of Purest Green": 415,
        "Challenge Loot: The Happiest Color": 416,
        "Challenge Loot: Purple Haze": 417,
        "Challenge Loot: Junkyard Dog": 418,
        "Challenge Low Gravity: Eagle Eye": 419,
        "Challenge Low Gravity: Slampage!": 420,
        "Challenge Low Gravity: Roger Slamjet": 421,
        "Challenge Low Gravity: Boosted": 422,
        "Challenge Low Gravity: Death from Above": 423,
        "Challenge Low Gravity: Dragon Punch": 424,
        "Challenge Misc: We Have a Contender": 425,
        "Challenge Misc: OC/DC": 426,
        "Challenge Misc: Little on the Side": 427,
        "Challenge Tycho's Ribs: That Was Your Own Fault...": 428,
        "Challenge Tycho's Ribs: Mystery of the Crystal Skulls": 429,
        "Challenge Tycho's Ribs: Cult of the Vault": 430,
        "Challenge Serenity's Waste: Phonically Challenged": 431,
        "Challenge Serenity's Waste: Cult of the Vault": 432,
        "Challenge Hyperion Hub of Heroism: Feed the Fishes": 433,
        "Challenge Hyperion Hub of Heroism: Flame Off": 434,
        "Challenge Hyperion Hub of Heroism: Oh, the Humanity": 435,
        "Challenge Hyperion Hub of Heroism: Perfect Dive": 436,
        "Challenge Hyperion Hub of Heroism: Playing Chicken": 437,
        "Challenge Hyperion Hub of Heroism: Cult of the Vault": 438,
        "Challenge Hyperion Hub of Heroism: Window Shopping": 439,
        "Challenge Crisis Scar: Red Last": 440,
        "Challenge Crisis Scar: Lava Leap": 441,
        "Challenge Crisis Scar: Up Magma": 442,
        "Challenge Crisis Scar: Cult of the Vault": 443,
        "Challenge Titan Industrial Facility: Fast Shooter": 444,
        "Challenge Titan Industrial Facility: Be Quick or Be Dead": 445,
        "Challenge Titan Industrial Facility: Breath Holder": 446,
        "Challenge Titan Industrial Facility: Cult of the Vault": 447,
        "Challenge Titan Robot Production Plant: Cult of the Vault": 448,
        "Challenge Titan Robot Production Plant: Turret Engineer": 449,
        "Challenge Titan Robot Production Plant: I Can Do This Alone": 450,
        "Challenge Regolith Range: Dead Set": 451,
        "Challenge Regolith Range: Dead Weight": 452,
        "Challenge Regolith Range: Insulated": 453,
        "Challenge Regolith Range: Cult of the Vault": 454,
        "Challenge Vorago Solitude: Mind the Gap": 455,
        "Challenge Vorago Solitude: Eridian Archaeology": 456,
        "Challenge Vorago Solitude: Vorago's Dig Sights": 457,
        "Challenge Vorago Solitude: Cult of the Vault": 458,
        "Challenge Pity's Fall: You Call That a Shield?": 459,
        "Challenge Pity's Fall: A Conventional Death": 460,
        "Challenge Pity's Fall: Engineering 201": 461,
        "Challenge Pity's Fall: Bosun's Mate": 462,
        "Challenge Pity's Fall: Cult of the Vault": 463,
        "Challenge Eye of Helios: Finish Him": 464,
        "Challenge Eye of Helios: Loose Cannon": 465,
        "Challenge Eye of Helios: Power Play": 466,
        "Challenge Eye of Helios: Training Day": 467,
        "Challenge Eye of Helios: Tread Carefully": 468,
        "Challenge Eye of Helios: Cult of the Vault": 469,
        "Challenge Eleseer: One Step Ahead of You": 470,
        "Challenge Eleseer: Cult of the Vault": 471,
        "Challenge Eleseer: Aim for the Little Ones": 472,
        "Challenge Veins of Helios: Cannibal Corpse": 473,
        "Challenge Veins of Helios: Catch a Ride": 474,
        "Challenge Veins of Helios: Honorary Foreman": 475,
        "Challenge Veins of Helios: Jump for Joy": 476,
        "Challenge Veins of Helios: Thrill Seeker": 477,
        "Challenge Veins of Helios: Cult of the Vault": 478,
        "Challenge Jack's Office: Fiery Filer": 479,
        "Challenge Jack's Office: Cult of the Vault": 480,
        "Challenge Abandoned Training Facility: Jack Be Nimble": 481,
        "Challenge Abandoned Training Facility: Best Served Hot": 482,
        "Challenge Abandoned Training Facility: Cult of the Vault": 483,
        "Challenge Stanton's Liver: Hidden Treasure": 484,
        "Challenge Stanton's Liver: Killing Time": 485,
        "Challenge Stanton's Liver: Leap of Faith": 486,
        "Challenge Stanton's Liver: Cult of the Vault": 487,
        "Challenge Outlands Spur: Boomer's Bane": 488,
        "Challenge Outlands Spur: OHS Inspection": 489,
        "Challenge Outlands Spur: Pickle Picker": 490,
        "Challenge Outlands Spur: Cult of the Vault": 491,
        "Challenge Outlands Canyon: King of the Hill": 492,
        "Challenge Outlands Canyon: No Animal Harmed": 493,
        "Challenge Outlands Canyon: Perfect Timing": 494,
        "Challenge Outlands Canyon: Cult of the Vault": 495,
        "Challenge Research and Development: Data Recovery": 496,
        "Challenge Research and Development: Feed the Fish": 497,
        "Challenge Research and Development: Hook Shot": 498,
        "Challenge Research and Development: Leap of Faith II": 499,
        "Challenge Research and Development: Cult of the Vault": 500,
        "Challenge Research and Development: Can't See Me": 501,
        "Challenge Concordia: Clairvoyant": 502,
        "Challenge Concordia: Doin' the Robot": 503,
        "Challenge Concordia: It's a Fair Cop": 504,
        "Challenge Concordia: Jackpot!": 505,
        "Challenge Concordia: Cult of the Vault": 506,
        "Challenge Sub-Level 13: Cult of the Vault": 507,
        "Challenge Tycho's Ribs: History of Elpis' Interior": 508,
        "Challenge Vorago Solitude: Entirely Metal Outerwear": 509,
        "Challenge Stanton's Liver: Digging up the Past": 510,
        "Challenge Hyperion Hub of Heroism: Wise Owl": 511,
        "Challenge Hyperion Hub of Heroism: Interplanetary Ninja Chatterbox": 512,
        "Challenge Hyperion Hub of Heroism: Hard Knocks": 513,
        "Challenge Hyperion Hub of Heroism: Robotic Aspirations": 514,
        "Challenge Claptrap: Clean Sweep": 515,
        "Challenge Claptrap: Claptomaniac": 516,
        "Challenge Claptrap: Volakillity": 517,
        "Challenge Claptrap: I Like Surprises...": 518,
        "Challenge Claptrap: 99 Problems and a Glitch Aint One": 519,
        "Challenge Deck 13 \u00bd: Cult of the Vault": 520,
        "Challenge Deck 13.5: Platform Panic": 521,
        "Challenge Deck 13.5: Cult of the Vault": 522,
        "Challenge Cluster 00773 P4ND0R4: Cult of the Vault": 523,
        "Challenge Cluster 00773 P4ND0R4: Void Rage": 524,
        "Challenge Motherlessboard: Advanced Search": 525,
        "Challenge Motherlessboard: Bandwidth Hog": 526,
        "Challenge Motherlessboard: Board Jumper": 527,
        "Challenge Motherlessboard: Cult of the Vault": 528,
        "Challenge The Nexus: Dodgewall": 529,
        "Challenge The Nexus: Cult of the Vault": 530,
        "Challenge Cluster 99002 0V3RL00K: My Balloons! Those are my Balloons!": 531,
        "Challenge Cluster 99002 0V3RL00K: Faptrap": 532,
        "Challenge Cluster 99002 0V3RL00K: Cult of the Vault": 533,
        "Challenge The Cortex: Circuit Jumper": 534,
        "Challenge The Cortex: Cult of the Vault": 535,
        "Challenge Subconscious: Bobble, Bobble, Soil and Rubble": 536,
        "Challenge Subconscious: Finders Creepers": 537,
        "Challenge Subconscious: A Bubble for your Thoughts": 538,
        "Challenge Subconscious: Cult of the Vault": 539,
        "Challenge The Holodome: Power Surge": 540,
        "Challenge The Holodome: Take to the Skies": 541,
        "Challenge The Holodome: Cult of the Vault": 542,
        "Red Chest PandoraSimulation: B4D S3CT0R Tower": 543,
        "Red Chest PandoraSimulation: H-Source Room": 544,
        "Red Chest OverlookSimulation: Denial Subroutine Fight": 545,
        "Chest Concordia: Moxxi's Toy Box": 546,
        "Chest CrisisScar: Comms Facility Roof": 547,
        "Chest CrisisScar: Power Substation": 548,
        "Chest CrisisScar: RedBelly Chest #1": 549,
        "MoonChest CrisisScar: RedBelly Chest #2": 550,
        "Chest Eleseer: WSW corner": 551,
        "Special Eleseer: Collect Vault Symbol": 552,
        "MoonChest EyeOfHelios: Laser Catwalk": 553,
        "MoonChest EyeOfHelios: Above Laser Exit": 554,
        "Chest Intro: Behind That Asshole": 555,
        "Chest HubOfHeroism: Central Terminal": 556,
        "Chest HubOfHeroism: World of Shopping": 557,
        "Chest HubOfHeroism: Hall of Wonders": 558,
        "Chest Launching Station: Power Core Alpha": 559,
        "Chest Launching Station: Power Core Beta": 560,
        "Chest JacksOffice: Secret Chest": 561,
        "Chest Motherlessboard: Memory Bank 4": 562,
        "MoonChest OutfallPumpingStation: MKV Reward": 563,
        "Chest OutlandsCanyon: Bogan's Warren": 564,
        "Chest OutlandsCanyon: Research Facility": 565,
        "Chest OutlandsCanyon: House Overlooking BBall Court": 566,
        "Chest OutlandsSpur: Processing Plant": 567,
        "Chest OutlandsSpur: Pumping Station": 568,
        "Chest OutlandsSpur: Top of Treatment Plant": 569,
        "Chest PitysFall: Starboard Ascent": 570,
        "Chest PitysFall: Hangar Bay": 571,
        "MoonChest PitysFall: Engineering": 572,
        "MoonChest PitysFall: AI Hub": 573,
        "Chest PitysFall: AI Hub": 574,
        "Chest PitysFall: The Secret Chamber Reward": 575,
        "Chest RegolithRange: Deadlift Chest #1": 576,
        "Chest RegolithRange: Deadlift Chest #2": 577,
        "MoonChest RegolithRange: Waystation Tower Roof": 578,
        "Chest RegolithRange: Last Requests Reward": 579,
        "Chest RnD: Aquarium": 580,
        "Chest RnD: Synaptic Processing Chest #1": 581,
        "Chest RnD: Synaptic Processing Chest #2": 582,
        "Special RnD: Pet Benjamin Blue": 583,
        "Chest StantonsLiver: Piraud's Thrutch": 584,
        "Chest SubLevel13: Vents": 585,
        "Chest SubLevel13: ControlRoom": 586,
        "Chest Subconscious:Terrorhead Gorge": 587,
        "Chest Subconscious: The Sum of Some Fears": 588,
        "Chest Subconscious: Top of Sub-Subconscious": 589,
        "Red Chest Cortex: SH4D0W-TP Chest #1": 590,
        "Red Chest Cortex: SH4D0W-TP Chest #2": 591,
        "GlitchChest Cortex: l33t h4X0rz reward #1": 592,
        "GlitchChest Cortex: l33t h4X0rz reward #2": 593,
        "Chest TitanIndustrialFacility: Stingray Factory: Atrium": 594,
        "Chest TitanIndustrialFacility: Stingray Factory: Main Hall": 595,
        "MoonChest TitanRobotPlant: Locomotion Assembly": 596,
        "MoonChest TitanRobotPlant: Unit Embarkation": 597,
        "Chest TitanRobotPlant: Unit Embarkation #1": 598,
        "Chest TitanRobotPlant: Unit Embarkation #2": 599,
        "Chest TitanRobotPlant: Unit Embarkation #3": 600,
        "Red Chest TritonFlats: Chunder's Hole": 601,
        "Red Chest TritonFlats: Flinder's Needle": 602,
        "Red Chest TritonFlats: The Grabba": 603,
        "Chest TychosRibs: Compression Chamber": 604,
        "Chest TychosRibs: Particle Collection Chamber": 605,
        "Chest TychosRibs: Easter Egg Main Chest": 606,
        "Chest TychosRibs: Easter Egg Secret Chest": 607,
        "Chest TychosRibs: Exhaust Port": 608,
        "Chest VeinsOfHelios: South Chest": 609,
        "Chest VeinsOfHelios: Don't Get Cocky Reward #1": 610,
        "Chest VeinsOfHelios: Don't Get Cocky Reward #2": 611,
        "Chest VeinsOfHelios: Don't Get Cocky Reward #3": 612,
        "Chest VeinsOfHelios: North Chest": 613,
        "Chest VoragoSolitude: East Pumping Station": 614,
        "Chest VoragoSolitude: Solitude Junction": 615,
        "Chest VoragoSolitude: Solitude's Edge": 616,
        "Chest RegolithRange: Leaning Tower Roof": 617,
        "Chest Holodome: Vault Keys Reward #1": 618,
        "Chest Holodome: Vault Keys Reward #2": 619,
        "Chest Holodome: Vault Keys Reward #3": 620,
        "Chest Nexus: H0N3Y-P0T Chest": 621,
        "GlitchChest Nexus: Trash Compactor": 622,
        "Chest Motherlessboard: Quantum Shunt": 623,
        "Common Shield Found": 624,
        "Uncommon Shield Found": 625,
        "Rare Shield Found": 626,
        "VeryRare Shield Found": 627,
        "Legendary Shield Found": 628,
        "Unique Shield Found": 629,
        "Common GrenadeMod Found": 630,
        "Uncommon GrenadeMod Found": 631,
        "Rare GrenadeMod Found": 632,
        "VeryRare GrenadeMod Found": 633,
        "Legendary GrenadeMod Found": 634,
        "Unique GrenadeMod Found": 635,
        "Common ClassMod Found": 636,
        "Uncommon ClassMod Found": 637,
        "Rare ClassMod Found": 638,
        "VeryRare ClassMod Found": 639,
        "Legendary ClassMod Found": 640,
        "Common Oz Kit Found": 641,
        "Uncommon Oz Kit Found": 642,
        "Rare Oz Kit Found": 643,
        "VeryRare Oz Kit Found": 644,
        "Legendary Oz Kit Found": 645,
        "Unique Oz Kit Found": 646,
        "Common Pistol Found": 647,
        "Uncommon Pistol Found": 648,
        "Rare Pistol Found": 649,
        "VeryRare Pistol Found": 650,
        "Legendary Pistol Found": 651,
        "Glitch Pistol Found": 652,
        "Unique Pistol Found": 653,
        "Common Shotgun Found": 654,
        "Uncommon Shotgun Found": 655,
        "Rare Shotgun Found": 656,
        "VeryRare Shotgun Found": 657,
        "Legendary Shotgun Found": 658,
        "Glitch Shotgun Found": 659,
        "Unique Shotgun Found": 660,
        "Common SMG Found": 661,
        "Uncommon SMG Found": 662,
        "Rare SMG Found": 663,
        "VeryRare SMG Found": 664,
        "Legendary SMG Found": 665,
        "Glitch SMG Found": 666,
        "Unique SMG Found": 667,
        "Common SniperRifle Found": 668,
        "Uncommon SniperRifle Found": 669,
        "Rare SniperRifle Found": 670,
        "VeryRare SniperRifle Found": 671,
        "Legendary SniperRifle Found": 672,
        "Glitch SniperRifle Found": 673,
        "Unique SniperRifle Found": 674,
        "Common AssaultRifle Found": 675,
        "Uncommon AssaultRifle Found": 676,
        "Rare AssaultRifle Found": 677,
        "VeryRare AssaultRifle Found": 678,
        "Legendary AssaultRifle Found": 679,
        "Glitch AssaultRifle Found": 680,
        "Unique AssaultRifle Found": 681,
        "Common RocketLauncher Found": 682,
        "Uncommon RocketLauncher Found": 683,
        "Rare RocketLauncher Found": 684,
        "VeryRare RocketLauncher Found": 685,
        "Legendary RocketLauncher Found": 686,
        "Glitch RocketLauncher Found": 687,
        "Unique RocketLauncher Found": 688,
        "Common Laser Found": 689,
        "Uncommon Laser Found": 690,
        "Rare Laser Found": 691,
        "VeryRare Laser Found": 692,
        "Legendary Laser Found": 693,
        "Glitch Laser Found": 694,
        "Unique Laser Found": 695,
        "Quest: Welcome to Helios": 696,
        "Quest: Lost Legion Invasion": 697,
        "Quest: Land Among the Stars": 698,
        "Quest: Follow Your Heart": 699,
        "Quest: Tales from Elpis": 700,
        "Quest: Last Requests": 701,
        "Quest: Marooned": 702,
        "Quest: Nova? No Problem!": 703,
        "Quest: Torgue-o! Torgue-o!": 704,
        "Quest: Systems Jammed": 705,
        "Quest: Wherefore Art Thou?": 706,
        "Quest: The Empty Billabong": 707,
        "Quest: All the Little Creatures": 708,
        "Quest: Recruitment Drive": 709,
        "Quest: A New Direction": 710,
        "Quest: Bunch of Ice Holes": 711,
        "Quest: Grinders": 712,
        "Quest: Pop Racing": 713,
        "Quest: To Arms!": 714,
        "Quest: Zapped 1.0": 715,
        "Quest: Zapped 2.0": 716,
        "Quest: Zapped 3.0": 717,
        "Quest: Boomshakalaka": 718,
        "Quest: Space Slam": 719,
        "Quest: Intelligences of the Artificial Persuasion": 720,
        "Quest: The Secret Chamber": 721,
        "Quest: Wiping the Slate": 722,
        "Quest: No Such Thing as a Free Launch": 723,
        "Quest: Nothing is Never an Option": 724,
        "Quest: Treasures of ECHO Madre": 725,
        "Quest: Another Pickle": 726,
        "Quest: Home Delivery": 727,
        "Quest: Rough Love": 728,
        "Quest: Let's Build a Robot Army": 729,
        "Quest: Sub-Level 13": 730,
        "Quest: Sub-Level 13: Part 2": 731,
        "Quest: The Voyage of Captain Chef": 732,
        "Quest: Home Sweet Home": 733,
        "Quest: Hot Head": 734,
        "Quest: Voice Over": 735,
        "Quest: Boarding Party": 736,
        "Quest: An Urgent Message": 737,
        "Quest: Handsome AI": 738,
        "Quest: Paint Job": 739,
        "Quest: Kill Meg": 740,
        "Quest: Science and Violence": 741,
        "Quest: Infinite Loop": 742,
        "Quest: Fresh Air": 743,
        "Quest: It Ain't Rocket Surgery": 744,
        "Quest: Lab 19": 745,
        "Quest: Cleanliness Uprising": 746,
        "Quest: Watch Your Step": 747,
        "Quest: Red, Then Dead": 748,
        "Quest: Things That Go Boom": 749,
        "Quest: To the Moon": 750,
        "Quest: Lock and Load": 751,
        "Quest: Quarantine: Back On Schedule": 752,
        "Quest: Quarantine: Infestation": 753,
        "Quest: In Perfect Hibernation": 754,
        "Quest: Trouble with Space Hurps": 755,
        "Quest: Don't Get Cocky": 756,
        "Quest: Eradicate!": 757,
        "Quest: Eye to Eye": 758,
        "Quest: Picking Up the Pieces": 759,
        "Quest: These are the Bots": 760,
        "Quest: The Don": 761,
        "Quest: Return of Captain Chef": 762,
        "Quest: Don't Shoot the Messenger": 763,
        "Quest: Z8N-TP": 764,
        "Quest: The Beginning of the End": 765,
        "Quest: The Bestest Story Ever Told": 766,
        "Quest: Guardian Hunter": 767,
        "Quest: Sterwin Forever": 768,
        "Quest: DAHL Combat Training: Round 1": 769,
        "Quest: DAHL Combat Training: Round 2": 770,
        "Quest: DAHL Combat Training: Round 3": 771,
        "Quest: DAHL Combat Training: Round 4": 772,
        "Quest: DAHL Combat Training: Round 5": 773,
        "Quest: Alpha": 774,
        "Quest: Beta": 775,
        "Quest: Delta": 776,
        "Quest: Gamma": 777,
        "Quest: l33t h4X0rz": 778,
        "Quest: Enter the Claptrap": 779,
        "Quest: File Search": 780,
        "Quest: END OF LINE": 781,
        "Quest: System Shutdown": 782,
        "Quest: The Psychology of a Claptrap": 783,
        "Quest: A Deadlier Game": 784,
        "Quest: Byte Club": 785,
        "Quest: Chip's Data Mining Adventure": 786,
        "Quest: 3G0-TP": 787,
        "Quest: 1D-TP": 788,
        "Quest: Rose Tinting": 789,
        "Quest: Corrosion of Dignity": 790,
        "Quest: Spyware Who Came in from the Cold": 791,
        "Quest: You Can Stop the Music": 792,
        "Quest: The Sum of Some Fears": 793,
        "Quest: 5UP4-3G0-TP": 794,
        "Quest: The Temple of Boom": 795,
        "Quest: h4X0rz": 796,
        "Quest: Digistructed Madness: Round 1": 797,
        "Quest: Digistructed Madness: Round 2": 798,
        "Quest: Digistructed Madness: Round 3": 799,
        "Quest: Digistructed Madness: Round 4": 800,
        "Quest: Digistructed Madness: Round 5": 801,
        "Quest: Digistructed Madness: The Badass Round": 802
    },
    "item": {
        "3 Skill Points": 1,
        "3 Skill Points (p)": 2,
        "Progressive Money Cap": 3,
        "Progressive Weapon Slot": 4,
        "$100": 5,
        "10 Moonstones": 6,
        "Progressive Jump": 7,
        "Melee": 8,
        "Crouch": 9,
        "Progressive Sprint": 10,
        "Vehicle Fire": 11,
        "10% Exp": 12,
        "Travel: Abandoned Training Facility": 13,
        "Travel: Cluster 00773 P4ND0R4": 14,
        "Travel: Cluster 99002 0V3RL00K": 15,
        "Travel: Concordia": 16,
        "Travel: Crisis Scar": 17,
        "Travel: Deck 13 \u00bd": 18,
        "Travel: Deck 13.5": 19,
        "Travel: Eleseer": 20,
        "Travel: Eye of Helios": 21,
        "Travel: Hyperion Hub of Heroism": 22,
        "Travel: Jack's Office": 23,
        "Travel: Lunar Launching Station": 24,
        "Travel: Motherlessboard": 25,
        "Travel: Outfall Pumping Station": 26,
        "Travel: Outlands Canyon": 27,
        "Travel: Outlands Spur": 28,
        "Travel: Pity's Fall": 29,
        "Travel: Regolith Range": 30,
        "Travel: Research and Development": 31,
        "Travel: Serenity's Waste": 32,
        "Travel: Stanton's Liver": 33,
        "Travel: Sub-Level 13": 34,
        "Travel: Subconscious": 35,
        "Travel: The Cortex": 36,
        "Travel: The Holodome": 37,
        "Travel: The Meriff's Office": 38,
        "Travel: The Nexus": 39,
        "Travel: Titan Industrial Facility": 40,
        "Travel: Titan Robot Production Plant": 41,
        "Travel: Triton Flats": 42,
        "Travel: Tycho's Ribs": 43,
        "Travel: Veins of Helios": 44,
        "Travel: Vorago Solitude": 45,
        "Progressive Travel: Base Game": 46,
        "Progressive Travel: Side Area": 47,
        "Progressive Travel: The Holodome Onslaught DLC": 48,
        "Progressive Travel: Shock Drop Slaughter Pit DLC": 49,
        "Progressive Travel: Claptastic Voyage DLC": 50,
        "Trap Spawn: Opha": 51,
        "Trap Spawn: Slippery": 52,
        "Trap Spawn: Item Explosion": 53,
        "Override Level 15": 54,
        "Override Level 30": 55,
        "Max Ammo Pistol": 56,
        "Max Ammo Shotgun": 57,
        "Max Ammo SMG": 58,
        "Max Ammo SniperRifle": 59,
        "Max Ammo AssaultRifle": 60,
        "Max Ammo RocketLauncher": 61,
        "Max Ammo Laser": 62,
        "Max Grenade Count": 63,
        "Backpack Upgrade": 64,
        "Filler Gear: Bad Touch": 65,
        "Filler Gear: Cyber Eagle": 66,
        "Filler Gear: Ack Ack": 67,
        "Filler Gear: 3DD1.E": 68,
        "Filler Gear: Freedom": 69,
        "Filler Gear: Invigoration": 70,
        "Filler Gear: Moonlight Saga": 71,
        "Filler Gear: Oxidizer": 72,
        "Filler Gear: Cathartic": 73,
        "Filler Gear: Springs'": 74,
        "Filler Gear: Support Relay": 75,
        "Filler Gear: Systems Purge": 76,
        "Filler Gear: Bullpup": 77,
        "Filler Gear: Smasher": 78,
        "Filler Gear: Gwens Other Head": 79,
        "Filler Gear: Good Touch": 80,
        "Filler Gear: Ice Scream": 81,
        "Filler Gear: Wallop": 82,
        "Filler Gear: Hail": 83,
        "Filler Gear: Ol' Painful": 84,
        "Filler Gear: Mining Laser": 85,
        "Filler Gear: Firestarta": 86,
        "Filler Gear: Freezeeasy": 87,
        "Filler Gear: Vibra Pulse": 88,
        "Filler Gear: SavorySideSaber": 89,
        "Filler Gear: Vandergraffen": 90,
        "Filler Gear: Ol' Rosie": 91,
        "Filler Gear: E-GUN": 92,
        "Filler Gear: Volt Thrower": 93,
        "Filler Gear: Creamer": 94,
        "Filler Gear: Globber": 95,
        "Filler Gear: Fibber": 96,
        "Filler Gear: Moonface": 97,
        "Filler Gear: Boganella": 98,
        "Filler Gear: Heart Breaker": 99,
        "Filler Gear: Octo": 100,
        "Filler Gear: Wombat": 101,
        "Filler Gear: Too Scoops": 102,
        "Filler Gear: Boomacorn": 103,
        "Filler Gear: Jack-O'-Cannon": 104,
        "Filler Gear: Mareks Mouth": 105,
        "Filler Gear: Meat Grinder": 106,
        "Filler Gear: Fridgia": 107,
        "Filler Gear: Frostfire": 108,
        "Filler Gear: Black Snake": 109,
        "Filler Gear: Wet Week": 110,
        "Filler Gear: Fremington's Edge": 111,
        "Filler Gear: Razorback": 112,
        "Filler Gear: Ch\u00e8re-amie": 113,
        "Filler Gear: The Machine": 114,
        "Filler Gear: Lady Fist": 115,
        "Filler Gear: E-Gun": 116,
        "Filler Gear: Torguemada": 117,
        "Filler Gear: Moxxi's Probe": 118,
        "Filler Gear: Boss Nova": 119,
        "Filler Gear: Tannis' Laser of Enlightenment": 120,
        "Filler Gear: Minac's Atonement": 121,
        "Filler Gear: Party Popper": 122,
        "Filler Gear: Hard Reboot": 123,
        "Filler Gear: Company Man": 124,
        "Filler Gear: Moonscaper": 125,
        "Filler Gear: Fast Talker": 126,
        "Filler Gear: Shield Of Ages": 127,
        "Filler Gear: Naught": 128,
        "Filler Gear: Heartfull Splodger": 129,
        "Filler Gear: Cutie Killer": 130,
        "Filler Gear: Perdy Lights": 131,
        "Filler Gear: Haymaker": 132,
        "Filler Gear: Deadly Bloom": 133,
        "Filler Gear: Asteroid Belt": 134,
        "Filler Gear: Rapid Release": 135,
        "Filler Gear: Sunshine": 136,
        "Filler Gear: Slammer": 137,
        "Filler Gear: Data Scrubber": 138,
        "Filler Gear: Baby Boomer": 139,
        "Filler Gear: Contraband Sky Rocket": 140,
        "Filler Gear: Snowball": 141,
        "Filler Gear: Kiss of Death": 142,
        "Filler Gear: Monster Trap": 143,
        "Filler Gear: Avalanche": 144,
        "Filler Gear: Shooting Star": 145,
        "Filler Gear: The Sham": 146,
        "Filler Gear: Kala": 147,
        "Filler Gear: Prismatic Bulwark": 148,
        "Filler Gear: Black Hole": 149,
        "Filler Gear: Supernova": 150,
        "Filler Gear: Fabled Tortoise": 151,
        "Filler Gear: Reogenator": 152,
        "Filler Gear: Whisky Tango Foxtrot": 153,
        "Filler Gear: Bigg Thumppr": 154,
        "Filler Gear: The Cradle": 155,
        "Filler Gear: Flyin' Maiden": 156,
        "Filler Gear: Bonus Package": 157,
        "Filler Gear: Quasar": 158,
        "Filler Gear: Bouncing Bazza": 159,
        "Filler Gear: Fire Bee": 160,
        "Filler Gear: Four Seasons": 161,
        "Filler Gear: Leech": 162,
        "Filler Gear: Nasty Surprise": 163,
        "Filler Gear: Pandemic": 164,
        "Filler Gear: Rolling Thunder": 165,
        "Filler Gear: Storm Front": 166,
        "Filler Gear: Excalibastard": 167,
        "Filler Gear: Longnail": 168,
        "Filler Gear: Torrent": 169,
        "Filler Gear: Striker": 170,
        "Filler Gear: KerBoom": 171,
        "Filler Gear: Cryophobia": 172,
        "Filler Gear: The ZX-1": 173,
        "Filler Gear: Fatale": 174,
        "Filler Gear: Blowfly": 175,
        "Filler Gear: Nukem": 176,
        "Filler Gear: Zim": 177,
        "Filler Gear: Hammer Buster II": 178,
        "Filler Gear: Skullmasher": 179,
        "Filler Gear: Flakker": 180,
        "Filler Gear: Invader": 181,
        "Filler Gear: Thingy": 182,
        "Filler Gear: Sledge's Shotty": 183,
        "Filler Gear: IVF": 184,
        "Filler Gear: Shredifier": 185,
        "Filler Gear: Major Tom": 186,
        "Filler Gear: Min Min Lighter": 187,
        "Filler Gear: Cat o' Nine Tails": 188,
        "Filler Gear: Badaboom": 189,
        "Filler Gear: Mongol": 190,
        "Filler Gear: Shooterang": 191,
        "Filler Gear: 88 Fragnum": 192,
        "Filler Gear: Maggie": 193,
        "Filler Gear: Logan's Gun": 194,
        "Filler Gear: Viral Marketer": 195,
        "Filler Gear: HellFire": 196,
        "Filler Gear: Pitchfork": 197,
        "Filler Gear: Magma": 198,
        "Filler Gear: Perfect Hibernation": 199,
        "Filler Gear: Fusillade": 200,
        "Filler Gear: Longest Yard": 201,
        "Filler Gear: Absolute Zero": 202,
        "Filler Gear: Thunderfire": 203,
        "Filler Gear: Laser Disker": 204,
        "Filler Gear: Luck Cannon": 205,
        "Filler Gear: Kaneda's Laser": 206,
        "Filler Gear: Cheat Code": 207,
        "Filler Gear: Omni-Cannon": 208,
        "Filler Gear: Proletarian Revolution": 209,
        "Filler Gear: Meganade": 210,
        "Filler Gear: M0RQ": 211,
        "Filler Gear: Rerouter": 212,
        "Filler Gear: Flayer": 213,
        "Filler Gear: Berrigan": 214,
        "Filler Gear: Cry Baby": 215,
        "Filler Gear: T4s-R": 216,
        "Filler Gear: Party Line": 217,
        "Filler Gear: Boxxy Gunn": 218,
        "Filler Gear: Plunkett": 219,
        "License: Common Shield": 220,
        "License: Uncommon Shield": 221,
        "License: Rare Shield": 222,
        "License: VeryRare Shield": 223,
        "License: Legendary Shield": 224,
        "License: Unique Shield": 225,
        "License: Common GrenadeMod": 226,
        "License: Uncommon GrenadeMod": 227,
        "License: Rare GrenadeMod": 228,
        "License: VeryRare GrenadeMod": 229,
        "License: Legendary GrenadeMod": 230,
        "License: Unique GrenadeMod": 231,
        "License: Common ClassMod": 232,
        "License: Uncommon ClassMod": 233,
        "License: Rare ClassMod": 234,
        "License: VeryRare ClassMod": 235,
        "License: Legendary ClassMod": 236,
        "License: Common Oz Kit": 237,
        "License: Uncommon Oz Kit": 238,
        "License: Rare Oz Kit": 239,
        "License: VeryRare Oz Kit": 240,
        "License: Legendary Oz Kit": 241,
        "License: Unique Oz Kit": 242,
        "License: Common Pistol": 243,
        "License: Uncommon Pistol": 244,
        "License: Rare Pistol": 245,
        "License: VeryRare Pistol": 246,
        "License: Legendary Pistol": 247,
        "License: Glitch Pistol": 248,
        "License: Unique Pistol": 249,
        "License: Common Shotgun": 250,
        "License: Uncommon Shotgun": 251,
        "License: Rare Shotgun": 252,
        "License: VeryRare Shotgun": 253,
        "License: Legendary Shotgun": 254,
        "License: Glitch Shotgun": 255,
        "License: Unique Shotgun": 256,
        "License: Common SMG": 257,
        "License: Uncommon SMG": 258,
        "License: Rare SMG": 259,
        "License: VeryRare SMG": 260,
        "License: Legendary SMG": 261,
        "License: Glitch SMG": 262,
        "License: Unique SMG": 263,
        "License: Common SniperRifle": 264,
        "License: Uncommon SniperRifle": 265,
        "License: Rare SniperRifle": 266,
        "License: VeryRare SniperRifle": 267,
        "License: Legendary SniperRifle": 268,
        "License: Glitch SniperRifle": 269,
        "License: Unique SniperRifle": 270,
        "License: Common AssaultRifle": 271,
        "License: Uncommon AssaultRifle": 272,
        "License: Rare AssaultRifle": 273,
        "License: VeryRare AssaultRifle": 274,
        "License: Legendary AssaultRifle": 275,
        "License: Glitch AssaultRifle": 276,
        "License: Unique AssaultRifle": 277,
        "License: Common RocketLauncher": 278,
        "License: Uncommon RocketLauncher": 279,
        "License: Rare RocketLauncher": 280,
        "License: VeryRare RocketLauncher": 281,
        "License: Legendary RocketLauncher": 282,
        "License: Glitch RocketLauncher": 283,
        "License: Unique RocketLauncher": 284,
        "License: Common Laser": 285,
        "License: Uncommon Laser": 286,
        "License: Rare Laser": 287,
        "License: VeryRare Laser": 288,
        "License: Legendary Laser": 289,
        "License: Glitch Laser": 290,
        "License: Unique Laser": 291,
        "Reward: Welcome to Helios": 292,
        "Reward: Lost Legion Invasion": 293,
        "Reward: Land Among the Stars": 294,
        "Reward: Follow Your Heart": 295,
        "Reward: Tales from Elpis": 296,
        "Reward: Last Requests": 297,
        "Reward: Marooned": 298,
        "Reward: Nova? No Problem!": 299,
        "Reward: Torgue-o! Torgue-o!": 300,
        "Reward: Systems Jammed": 301,
        "Reward: Wherefore Art Thou?": 302,
        "Reward: The Empty Billabong": 303,
        "Reward: All the Little Creatures": 304,
        "Reward: Recruitment Drive": 305,
        "Reward: A New Direction": 306,
        "Reward: Bunch of Ice Holes": 307,
        "Reward: Grinders": 308,
        "Reward: Pop Racing": 309,
        "Reward: To Arms!": 310,
        "Reward: Zapped 1.0": 311,
        "Reward: Zapped 2.0": 312,
        "Reward: Zapped 3.0": 313,
        "Reward: Boomshakalaka": 314,
        "Reward: Space Slam": 315,
        "Reward: Intelligences of the Artificial Persuasion": 316,
        "Reward: The Secret Chamber": 317,
        "Reward: Wiping the Slate": 318,
        "Reward: No Such Thing as a Free Launch": 319,
        "Reward: Nothing is Never an Option": 320,
        "Reward: Treasures of ECHO Madre": 321,
        "Reward: Another Pickle": 322,
        "Reward: Home Delivery": 323,
        "Reward: Rough Love": 324,
        "Reward: Let's Build a Robot Army": 325,
        "Reward: Sub-Level 13": 326,
        "Reward: Sub-Level 13: Part 2": 327,
        "Reward: The Voyage of Captain Chef": 328,
        "Reward: Home Sweet Home": 329,
        "Reward: Hot Head": 330,
        "Reward: Voice Over": 331,
        "Reward: Boarding Party": 332,
        "Reward: An Urgent Message": 333,
        "Reward: Handsome AI": 334,
        "Reward: Paint Job": 335,
        "Reward: Kill Meg": 336,
        "Reward: Science and Violence": 337,
        "Reward: Infinite Loop": 338,
        "Reward: Fresh Air": 339,
        "Reward: It Ain't Rocket Surgery": 340,
        "Reward: Lab 19": 341,
        "Reward: Cleanliness Uprising": 342,
        "Reward: Watch Your Step": 343,
        "Reward: Red, Then Dead": 344,
        "Reward: Things That Go Boom": 345,
        "Reward: To the Moon": 346,
        "Reward: Lock and Load": 347,
        "Reward: Quarantine: Back On Schedule": 348,
        "Reward: Quarantine: Infestation": 349,
        "Reward: In Perfect Hibernation": 350,
        "Reward: Trouble with Space Hurps": 351,
        "Reward: Don't Get Cocky": 352,
        "Reward: Eradicate!": 353,
        "Reward: Eye to Eye": 354,
        "Reward: Picking Up the Pieces": 355,
        "Reward: These are the Bots": 356,
        "Reward: The Don": 357,
        "Reward: Return of Captain Chef": 358,
        "Reward: Don't Shoot the Messenger": 359,
        "Reward: Z8N-TP": 360,
        "Reward: The Beginning of the End": 361,
        "Reward: The Bestest Story Ever Told": 362,
        "Reward: Guardian Hunter": 363,
        "Reward: Sterwin Forever": 364,
        "Reward: DAHL Combat Training: Round 1": 365,
        "Reward: DAHL Combat Training: Round 2": 366,
        "Reward: DAHL Combat Training: Round 3": 367,
        "Reward: DAHL Combat Training: Round 4": 368,
        "Reward: DAHL Combat Training: Round 5": 369,
        "Reward: Alpha": 370,
        "Reward: Beta": 371,
        "Reward: Delta": 372,
        "Reward: Gamma": 373,
        "Reward: l33t h4X0rz": 374,
        "Reward: Enter the Claptrap": 375,
        "Reward: File Search": 376,
        "Reward: END OF LINE": 377,
        "Reward: System Shutdown": 378,
        "Reward: The Psychology of a Claptrap": 379,
        "Reward: A Deadlier Game": 380,
        "Reward: Byte Club": 381,
        "Reward: Chip's Data Mining Adventure": 382,
        "Reward: 3G0-TP": 383,
        "Reward: 1D-TP": 384,
        "Reward: Rose Tinting": 385,
        "Reward: Corrosion of Dignity": 386,
        "Reward: Spyware Who Came in from the Cold": 387,
        "Reward: You Can Stop the Music": 388,
        "Reward: The Sum of Some Fears": 389,
        "Reward: 5UP4-3G0-TP": 390,
        "Reward: The Temple of Boom": 391,
        "Reward: h4X0rz": 392,
        "Reward: Digistructed Madness: Round 1": 393,
        "Reward: Digistructed Madness: Round 2": 394,
        "Reward: Digistructed Madness: Round 3": 395,
        "Reward: Digistructed Madness: Round 4": 396,
        "Reward: Digistructed Madness: Round 5": 397,
        "Reward: Digistructed Madness: The Badass Round": 398,
        "Filler Gear: Common Shield": 399,
        "Filler Gear: Uncommon Shield": 400,
        "Filler Gear: Rare Shield": 401,
        "Filler Gear: VeryRare Shield": 402,
        "Filler Gear: Legendary Shield": 403,
        "Filler Gear: Unique Shield": 404,
        "Filler Gear: Common GrenadeMod": 405,
        "Filler Gear: Uncommon GrenadeMod": 406,
        "Filler Gear: Rare GrenadeMod": 407,
        "Filler Gear: VeryRare GrenadeMod": 408,
        "Filler Gear: Legendary GrenadeMod": 409,
        "Filler Gear: Unique GrenadeMod": 410,
        "Filler Gear: Common ClassMod": 411,
        "Filler Gear: Uncommon ClassMod": 412,
        "Filler Gear: Rare ClassMod": 413,
        "Filler Gear: VeryRare ClassMod": 414,
        "Filler Gear: Legendary ClassMod": 415,
        "Filler Gear: Common Oz Kit": 416,
        "Filler Gear: Uncommon Oz Kit": 417,
        "Filler Gear: Rare Oz Kit": 418,
        "Filler Gear: VeryRare Oz Kit": 419,
        "Filler Gear: Legendary Oz Kit": 420,
        "Filler Gear: Unique Oz Kit": 421,
        "Filler Gear: Common Pistol": 422,
        "Filler Gear: Uncommon Pistol": 423,
        "Filler Gear: Rare Pistol": 424,
        "Filler Gear: VeryRare Pistol": 425,
        "Filler Gear: Legendary Pistol": 426,
        "Filler Gear: Glitch Pistol": 427,
        "Filler Gear: Unique Pistol": 428,
        "Filler Gear: Common Shotgun": 429,
        "Filler Gear: Uncommon Shotgun": 430,
        "Filler Gear: Rare Shotgun": 431,
        "Filler Gear: VeryRare Shotgun": 432,
        "Filler Gear: Legendary Shotgun": 433,
        "Filler Gear: Glitch Shotgun": 434,
        "Filler Gear: Unique Shotgun": 435,
        "Filler Gear: Common SMG": 436,
        "Filler Gear: Uncommon SMG": 437,
        "Filler Gear: Rare SMG": 438,
        "Filler Gear: VeryRare SMG": 439,
        "Filler Gear: Legendary SMG": 440,
        "Filler Gear: Glitch SMG": 441,
        "Filler Gear: Unique SMG": 442,
        "Filler Gear: Common SniperRifle": 443,
        "Filler Gear: Uncommon SniperRifle": 444,
        "Filler Gear: Rare SniperRifle": 445,
        "Filler Gear: VeryRare SniperRifle": 446,
        "Filler Gear: Legendary SniperRifle": 447,
        "Filler Gear: Glitch SniperRifle": 448,
        "Filler Gear: Unique SniperRifle": 449,
        "Filler Gear: Common AssaultRifle": 450,
        "Filler Gear: Uncommon AssaultRifle": 451,
        "Filler Gear: Rare AssaultRifle": 452,
        "Filler Gear: VeryRare AssaultRifle": 453,
        "Filler Gear: Legendary AssaultRifle": 454,
        "Filler Gear: Glitch AssaultRifle": 455,
        "Filler Gear: Unique AssaultRifle": 456,
        "Filler Gear: Common RocketLauncher": 457,
        "Filler Gear: Uncommon RocketLauncher": 458,
        "Filler Gear: Rare RocketLauncher": 459,
        "Filler Gear: VeryRare RocketLauncher": 460,
        "Filler Gear: Legendary RocketLauncher": 461,
        "Filler Gear: Glitch RocketLauncher": 462,
        "Filler Gear: Unique RocketLauncher": 463,
        "Filler Gear: Common Laser": 464,
        "Filler Gear: Uncommon Laser": 465,
        "Filler Gear: Rare Laser": 466,
        "Filler Gear: VeryRare Laser": 467,
        "Filler Gear: Legendary Laser": 468,
        "Filler Gear: Glitch Laser": 469,
        "Filler Gear: Unique Laser": 470
    }
}