# keys for this dictionary are either WillowAIPawn.AIClass.Name or WillowAIPawn.BalanceDefinitionState.BalanceDefinition.Name
enemy_class_to_loc_name = {
    "CharClass_DahlSergeant_Knuckle":                       "Enemy: Flame Knuckle",
    "CharClass_Ma_DataWorm":                                "Enemy: Denial Subroutine",
    "CharClass_Ned":                                        "Enemy: Red",
    "CharClass_Kelly":                                      "Enemy: Belly",
    "CharClass_RedBelly_Proxy":                             "Enemy: Red & Belly",
    "CharClass_BadassSpaceman":                             "Enemy: Bruce",
    "CharClass_LoaderUltimateBadass":                       "Enemy: Eclipse",
    "CharClass_EyeOfHelios":                                "Enemy: EOS",  #CharClass_Ma_Helios
    "CharClass_OphaBoss":                                   "Enemy: Opha Superior",
    "CharClass_MetaGuardian":                               "Enemy: The Sentinel",
    # "CharClass_MetaGuardian":                             "Enemy: The Invincible Sentinel", 
    # "CharClass_FBCBig_Face":                              "Enemy: The Invincible Empyrean Sentinel",  #CharClass_FBCBig
    "CharClass_ColZMech":                                   "Enemy: Colonel T. Zarpedon",
    "CharClass_ColZ":                                       "Enemy: Tungsteena Zarpedon, Ascended",
    "CharClass_DahlMarine_CentralTerm":                     "Enemy: Corporal Bob",
    "CharClass_Meg":                                        "Enemy: Meg",  #CharClass_Tentacle_Meg, CharClass_Tentacle_Meg_B
    "CharClass_Dean":                                       "Enemy: Dean",
    "CharClass_DahlRedShirt":                               "Enemy: Lost Legion Courier",
    "CharClass_DahlRedShirtPowersuit":                      "Enemy: Lost Legion Powersuit Noob",
    "CharClass_NPCInjuredSoldier":                          "Enemy: Surrendering Dahl Soldier",
    "CharClass_RabidAdams":                                 "Enemy: Rabid Adams",
    "CharClass_DrongoBones":                                "Enemy: Drongo Bones",
    "CharClass_BoomerJetFighter":                           "Enemy: Boomer",
    "CharClass_TonyTinCan":                                 "Enemy: Tony Slows",
    "CharClass_PoopDeck":                                   "Enemy: Poop Deck",
    "CharClass_Bosun":                                      "Enemy: Bosun",
    "CharClass_SpacemanDeadlift":                           "Enemy: Deadlift",
    "CharClass_Squat":                                      "Enemy: Squat",
    "CharClass_Stalker_RnD":                                "Enemy: X-STLK-23",
    "CharClass_DestroyerMini":                              "Enemy: Mini Destroyer",
    "CharClass_SonFlamey":                                  "Enemy: Son of Flamey",
    "PawnBalance_GrandsonFlamey":                                  "Enemy: Grandson of Flamey", #named minibeast
    "CharClass_UniqueCharger":                              "Enemy: Antagonized Kraggon",
    "CharClass_Rockzilla":                                  "Enemy: Iwajira",
    "CharClass_BadassTork":                                 "Enemy: Even-More-Disgusting Tork",
    "CharClass_ScavWastelandWalker":                        "Enemy: Swagman",
    "CharClass_RoosterBooster":                             "Enemy: Rooster Booster",
    "CharClass_Ma_Despair":                                 "Enemy: Despair",
    "CharClass_Ma_SelfLoathing":                            "Enemy: Self-Loathing",
    "CharClass_Ma_Sponx":                                   "Enemy: The Sponx",
    "CharClass_Ma_SH4D0W-TP":                               "Enemy: SH4D0W-TP",
    "CharClass_Ma_SelfEsteem":                              "Enemy: Self-Esteem",
    "CharClass_Ma_Hope":                                    "Enemy: Hope",
    "CharClass_LittleDarksiderBadassBandit":                "Enemy: Magma Rivers",
    "CharClass_DarksiderBadassBandit":                      "Enemy: Wally Wrong",
    "CharClass_DarksiderBadassPsycho":                      "Enemy: Fair Dinkum",
    "CharClass_CryoHive":                                   "Enemy: Giant Shuggurath of Ice",
    "PawnBalance_LunestalkerSnrRider":                      "Enemy: Lunestalker Sr.", #CharClass_ScavJetFighterRider 
    "PawnBalance_MaureenRider":                             "Enemy: Maureen",  #CharClass_ScavJetFighterRider
    "CharClass_MeatHead":                                   "Enemy: Meat Head",
    "CharClass_ScavSuicidePsycho":                          "Enemy: Oscar",
    # "CharClass_BoilGuard":                                "Enemy: Meat Is Murder", 
    # "CharClass_BoilWorker":                               "Enemy: Better With Butter", 
    # "CharClass_BoilWorker":                               "Enemy: One of Us", 
    # "CharClass_BoilWorker":                               "Enemy: Slimy Yet Satisfying", 
    # "CharClass_BoilWorker":                               "Enemy: Vegans Are Weird", 
    # "CharClass_HypRatWorker":                             "Enemy: Eat At Boil's", 
    # "CharClass_HypRatWorker":                             "Enemy: Free-Range, Farm-Fresh", 
    # "CharClass_HypRatWorker":                             "Enemy: Marinated Morsel", 
    # "CharClass_HypRatWorker":                             "Enemy: Yummy Down On This", 
    # "CharClass_HypRatWorker":                             "Enemy: Choice Cut", 
    "CharClass_Eghood":                                     "Enemy: Eghood",
    "CharacterClass_Clap_L3K":                              "Enemy: CL4P-L3K",
    "CharClass_ScavBandit":                                 "Enemy: Master Poacher",
    "CharClass_DanZando":                                   "Enemy: Dan Zando",
    "CharClass_Nel":                                        "Enemy: Nel",
    "CharClass_DahlCombatSuit_Felicity":                    "Enemy: Powersuit Felicity",
    "CharClass_Petunia_DestroyerMini":                      "Enemy: Defense Destroyer",
    "CharClass_DahlEternalPowersuit":                       "Enemy: Lost Legion Eternal Powersuit",
    "CharClass_GuardianPondor":                             "Enemy: Guardian Pondor",
    "CharClass_ElementalRider":                             "Enemy: Scavenger Beast",
    "CharClass_BanditRider":                                "Enemy: Scav Beast Rider",
    "CharClass_ElementalRider_Lil":                         "Enemy: Lil' Scavenger Beast",
    "CharClass_ScavBanditMidget_Rider":                     "Enemy: Lil' Scav",
    # "CharClass_Ma_Virus_Deletion":                        "Enemy: Reluctant Virus", 
    # "CharClass_Ma_Virus_Deletion":                        "Enemy: Ravenous Virus", 
    "CharacterClass_Ma_SuperEgoTrap":                       "Enemy: 5UP4-3G0-TP",
    "CharClass_Ma_MinacMinion":                             "Enemy: MINAC Minion",
    "CharacterClass_DignityTrap":                           "Enemy: D1GN1TY-TP",
    "CharClass_Ma_MiniTrojan_Shame":                        "Enemy: Shame",
    "CharClass_Ma_Chip":                                    "Enemy: Chip",
    "CharClass_Ma_Cookie":                                  "Enemy: Cookie",
    "CharClass_Ma_InsecurityBot":                           "Enemy: Minion",
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Catchy Hook!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Floor Filler!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Key Change!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Most Requested!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Sparkly Formula!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Tween Favorite!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Verse Chorus Verse Chorus Bridge Chorus (x2)!", 
    "CharClass_Ma_EarWorm":                                 "Enemy: Teh Earworm",
}
generic_enemy_lookup = {
    "Generic: Kraggon":                                     "_elemental",
    "Generic: Scav":                                        "_scavbandit",
    "Generic: Lunatic":                                     "scavengerpsycho",
    # "Generic: Lil' Scav":                                 "scavmidget",
    "Generic: Lil' Midget":                                 "midget",
    "Generic: Antagonized Kraggon":                         "_uniquecharger",
    "Generic: Tork":                                        "tork",
    # "Generic: Not-So-Cute Tork":                         "_notcutetork",
    # "Generic: Volatile Tork Swarming":                    "_torkswarmling_volatile",
    # "Generic: Tork Swarming":                             "_torkswarmling",
    "Generic: Scav SAM Turret":                             "_scav_rocketturret",
    "Generic: Freezing Rathyd":                             "_cryodunk",
    "Generic: Shuggurath of Ice":                           "_cryohive",
    # "Generic: Lil' Darksider":                            "_littledarksiderbandit",
    # "Generic: Madman`":                                   "_darksiderpsycho",
    # "Generic: Lil' Madman":                               "_littledarksiderpsycho",
    # "Generic: Darksider":                                 "_darksiderbandit",
    "Generic: Darksider":                                   "darksider",
    "Generic: Scav Laser Turret":                           "_scav_laserturret",
    # "Generic: Borrowed Laser Turret"":                    "_scav_laserturret",
    "Generic: Raider":                                      "_scavelitebandit",
    "Generic: Outlaw":                                      "spaceman",
    # "Generic: Badass Outlaw":                             "_badassspaceman",
    # "Generic: lil' Lunatic":                              "_scavpsychomidget",
    # "Generic: Lil' Outlaw":                               "_scavmidgetspaceman",
    "Generic: Stolen Dhal Jetfighter":                      "_scavjetfighter",
    # "Generic: Badass scav":                               "_scavbadassbandit",
    "Generic: Rathyd":                                      "_lesserrathyd",
    "Generic: Stinging Rathyd":                             "_rodunk",
    "Generic: Shuggurath":                                  "hive",
    # "Generic: Shuggurath":                                "_hiveflyer",
    # "Generic: Laser Moon Buggy":                          "_scavjetfighterrider",
    # "Generic: Energized shuggurath":                      "_shockhive",
    "Generic: Dhal SAM Turret":                             "_dahl_rocketturret",
    # "Generic: Bosuns' Shield Regenerator":                "_vsminiboss_heallaser",
    # "Generic: Badass Lil' Scav":                          "_scavbadassbanditmidget",
}