# These use the nicely formatted names
# TODO: potentially only need one per entrance. Not sure if they are all the right way round though
from BouncyLootGod.state import get_globals
entrance_to_req_areas = {
    # LevelTravelStationDefinition
    "Outlands2ToMoonSlaughter":                ["Outlands Canyon", "Abandoned Training Facility"],
    "MoonSlaughterToOutlands":                 ["Abandoned Training Facility", "Outlands Spur"],
    "AcessToDigsite":                          ["Tycho's Ribs", "Vorago Solitude"], #Acess is typo'd in the game files
    "HiddenMoonShotToAirstrip":                ["Serenity's Waste"],
    "ComFacilityToMoon":                       ["Crisis Scar", "Triton Flats"],
    "DahlFactoryToMoon":                       ["Titan Industrial Facility", "Triton Flats"],
    "DigSiteToMoonSurface":                    ["Vorago Solitude", "Serenity's Waste"],
    "LaserToInnerHull":                        ["Lunar Launching Station", "Veins of Helios"],
    "MoonCoreToShaft":                         ["FROM", "TO"],
    "SecretMoonToSpaceport":                   ["Triton Flats", "Concordia"],
    "OutlandsToOutlands2":                     ["Outlands Spur", "Outlands Canyon"],
    "Outlands2ToMoon":                         ["Outlands Canyon", "Triton Flats"],
    "RandDFacilityToCentralTerminal":          ["Research and Development", "Hyperion Hub of Heroism"],
    "SpaceportToAirstrip":                     ["Concordia", "Serenity's Waste"],
    "WreckToOutlands":                         ["Pity's Fall", "Outlands Spur"],
    "JacksOfficeToCentralTerminal":            ["Jack's Office", "Hyperion Hub of Heroism"],
    "DigSiteToShaft":                          ["Vorago Solitude", "TO"],
    "AcessToMoonCore":                         ["Tycho's Ribs", "TO"], #Acess is typo'd in the game files
    "AirstripToSpaceport":                     ["Serenity's Waste", "Concordia"],
    "MoonToComFacility":                       ["Triton Flats", "Crisis Scar"],
    "MoonToDahlFactory":                       ["Triton Flats", "Titan Industrial Facility"],
    "DeadsurfaceToMoonsurface":                ["Regolith Range", "Serenity's Waste"],
    "MoonsurfaceToDeadsurface":                ["Serenity's Waste", "Regolith Range"],
    "MoonSurfaceToDigSite":                    ["Serenity's Waste", "Vorago Solitude"],
    "Outfall_To_Vorago":                       ["Outfall Pumping Station", "Vorago Solitude"],
    "FactoryBossToFactory":                    ["Titan Robot Production Plant", "Titan Industrial Facility"],
    "FactoryToFactoryBoss":                    ["Titan Industrial Facility", "Titan Robot Production Plant"],
    "FactoryToSublevel13":                     ["Titan Industrial Facility", "Sub-Level 13"],
    "Sublevel13ToFactory":                     ["Sub-Level 13", "Titan Industrial Facility"],
    "MoonShotIntroToAirstrip":                 ["Serenity's Waste"],
    "LaserBossToLaser":                        ["Eye of Helios", "Lunar Launching Station"],
    "LaserToLaserBoss":                        ["Lunar Launching Station", "Eye of Helios"],
    "MeriffToSpaceport":                       ["The Meriff's Office", "Concordia"],
    "SpaceportToMeriff":                       ["Concordia", "The Meriff's Office"],
    "MoonSlaughterToWreck":                    ["Abandoned Training Facility", "Pity's Fall"],
    "MoonToOutlands":                          ["Triton Flats", "Outlands Spur"],
    "Vorago_To_Outfall":                       ["Vorago Solitude", "Outfall Pumping Station"],
    "Outlands2ToOutlands":                     ["Outlands Canyon", "Outlands Spur"],
    "OutlandsToWreck":                         ["Outlands Spur", "Pity's Fall"],
    "SecretSpaceportToMoon":                   ["Concordia", "Triton Flats"],
    "StantonsLiver_P":                         ["FROM", "TO"],
    "CentralTerminalToInnerHull":              ["Hyperion Hub of Heroism", "Veins of Helios"],
    "InnerHullToCentralTerminal":              ["Veins of Helios", "Hyperion Hub of Heroism"],
    "CentralTerminalToJacksOffice":            ["Hyperion Hub of Heroism", "Jack's Office"],
    "CentralTerminalToRandDFacility":          ["Hyperion Hub of Heroism", "Research and Development"],
    "InnerHullToLaser":                        ["Veins of Helios", "Lunar Launching Station"],
    "11B_ElevatortoDigsite":                   ["Tycho's Ribs", "Vorago Solitude"],
    "CoreVaultToMoonCore":                     ["FROM", "TO"],
    "ElevatorShaftToDigSite":                  ["Tycho's Ribs", "Vorago Solitude"],
    "RnDToDahlFactory":                        ["FROM", "Titan Industrial Facility"],
    "StantonsLiverToMoonSurface":              ["Stanton's Liver", "Serenity's Waste"],
    "MoonCoreToCoreVault":                     ["FROM", "TO"],
    "MoonSurfaceToStantonsLiver":              ["Serenity's Waste", "Stanton's Liver"],
    "11BElevatortoMoonCore":                   ["FROM", "TO"],
    "AirstripToMoonSurface":                   ["FROM", "Serenity's Waste"],
    "DahlFactoryToRnD":                        ["Titan Industrial Facility", "TO"],
    "DeadsurfaceToMoonsurfaceMoonZoomy":       ["Regolith Range", "Serenity's Waste"],
    "MoonsurfaceToDeadsurfaceMoonZoomy":       ["Serenity's Waste", "Regolith Range"],
    "Digsite_To_Rk5arena":                     ["FROM", "TO"],
    "DigsiteJunctionToDigsite":                ["FROM", "Vorago Solitude"],
    "DigSiteToDigsiteJunction":                ["Vorago Solitude", "TO"],
    "ElevatorShaftToMoonCore":                 ["FROM", "TO"],
    "FactoryBossToTerminal":                   ["FROM", "TO"],
    "TerminalToFactory":                       ["FROM", "TO"],
    "LabsToRnD":                               ["FROM", "TO"],
    "RnDToLabs":                               ["FROM", "TO"],
    "MainComFacilityToMoon":                   ["Crisis Scar", "Triton Flats"],
    "MainMoonToComFacility":                   ["Triton Flats", "Crisis Scar"],
    "MoonShaftToEridianSlaughter":             ["FROM", "TO"],
    "MoonSurfaceToAirstrip":                   ["Serenity's Waste", "Stanton's Liver"],
    "MoonToSpaceport":                         ["Triton Flats", "Concordia"],
    "SpaceportToMoon":                         ["Concordia", "Triton Flats"],
    "MoonToWaterfront":                        ["Triton Flats", "TO"],
    "MoonToWreck":                             ["Triton Flats", "Pity's Fall"],
    "WreckToMoon":                             ["Pity's Fall", "Triton Flats"],
    "OutlandsToMoon":                          ["Outlands Spur", "Triton Flats"],
    "OutlandsToMoonSlaughter":                 ["Outlands Spur", "Abandoned Training Facility"],
    "Rk5arena_To_Digsite":                     ["FROM", "TO"],
    "RnDToStationSlaughter":                   ["FROM", "TO"],
    "StationSlaughterToRnD":                   ["FROM", "TO"],
    "ShaftToDigSite":                          ["FROM", "Vorago Solitude"],
    "ShaftToMoonCore":                         ["FROM", "TO"],
    "SolitudeJunction":                        ["FROM", "TO"],
    # "SpaceportToNewHaven":                     ["Concordia", "TO"],
    "WaterfrontToMoon":                        ["FROM", "Triton Flats"],
    "WreckToMoonSlaughter":                    ["Pity's Fall", "Abandoned Training Facility"],
    "FinalBossToSubBoss":                      ["FROM", "TO"],
    "LeftToMotherboard":                       ["Cluster 00773 P4ND0R4", "Motherlessboard"],
    "NexusToDeck13":                           ["The Nexus", "Deck 13 ½"],
    "RightToMotherboard":                      ["Cluster 99002 0V3RL00K", "Motherlessboard"],
    "SubToNexus":                              ["Subconscious", "The Nexus"],
    "Deck13ToFinalBoss":                       ["Deck 13 ½", "TO"],
    "FinalBossToDeck13":                       ["FROM", "Deck 13 ½"],
    "Deck13toMotherboard":                     ["Deck 13 ½", "Motherlessboard"],
    "Deck13ToNexus":                           ["Deck 13 ½", "The Nexus"],
    "SubBossToFinalBoss":                      ["FROM", "Deck 13.5"],
    "MotherboardToLeft":                       ["Motherlessboard", "Cluster 00773 P4ND0R4"],
    "MotherboardToDeck13":                     ["Motherlessboard", "Deck 13 ½"],
    "MotherboardToNexus":                      ["Motherlessboard", "The Nexus"],
    "NexusToMotherboard":                      ["The Nexus", "Motherlessboard"],
    "MotherboardToRight":                      ["Motherlessboard", "Cluster 99002 0V3RL00K"],
    "NexusToSub":                              ["The Nexus", "Subconscious"],
    "SubBossToSub":                            ["FROM", "Subconscious"],
    "SubToSubBoss":                            ["Subconscious", "TO"],

    # FastTravelStationDefinition
    "Hunger":                        ["Gluttony Gulch"],
    "Xmas":                          ["Marcus's Mercenary Shop"],
    "BackburnerIntro":               ["The Backburner"],
    "BackBurner":                    ["The Backburner"],
    "Helios":                        ["Helios Fallen"],
    "OldDust":                       ["Dahl Abandon"],
    "ResearchCenter":                ["Mt. Scarab Research Center"],
    "Helios_OneWay":                 ["Helios Fallen"],
    "ResearchCenter_OneWay":         ["Mt. Scarab Research Center"],
    "SanctuaryIntro":                ["FFS Intro Sanctuary"],
    "Sandworm_OneWay":               ["The Burrows"],
    "CastleExterior":                ["Hatred's Shadow"],
    "CastleKeep":                    ["Dragon Keep"],
    "DarkForest":                    ["The Forest"],
    "DeadForest":                    ["Immortal Woods"],
    "Docks":                         ["Unassuming Docks"],
    "Dungeons":                      ["Lair of Infinite Agony"],
    "Mines":                         ["Mines of Avarice"],
    "Village":                       ["Flamerock Refuge"],
    "FyrestoneOneWay":               ["Arid Nexus Badlands"],
    "Interlude":                     ["The Dust"],
    "Lynchwood":                     ["Lynchwood"],
    "Outwash":                       ["Highlands Outwash"],
    "Sanctuary":                     ["Sanctuary"],
    "Wilhelm":                       ["End of the Line"],
    "Caverns":                       ["Caustic Caverns"],
    "DamTop":                        ["Bloodshot Ramparts"],
    # "Glacial":                       [],
    # "GlacialIgloo":                  [],
    "GoshDam":                       ["Bloodshot Stronghold"],
    "IceCanyon":                     ["Frostburn Canyon"],
    "IceEast":                       ["Three Horns Divide"],
    "IceWest":                       ["Three Horns Valley"],
    "SouthernShelfTown":             ["Southern Shelf"],
    "SouthpawFactory":               ["Southpaw Steam & Power"],
    "TundraExpress":                 ["Tundra Express"],
    "TundraExpressSecret":           ["Tundra Express"],
    "TundraTrain":                   ["End of the Line"],
    "Cliffs":                        ["Thousand Cuts"],
    "Cliffs_Boss":                   ["The Bunker"],
    "Grass_A":                       ["Highlands"],
    "Grass_B":                       ["Highlands"],
    "Grass_C":                       ["Highlands"],
    "HyperionCity":                  ["Opportunity"],
    "PandoraPark":                   ["Wildlife Exploitation Preserve"],
    "TheFridge":                     ["The Fridge"],
    "Ash":                           ["Eridium Blight"],
    "CraterLake":                    ["Sawtooth Cauldron"],
    "FinalBossAscent":               ["Hero's Pass"],
    "OnFireStone":                   ["Arid Nexus Boneyard"],
    "Volcano_Boss_A":                ["Vault of the Warrior"],
    "Volcano_Boss_B":                ["Vault of the Warrior"],
    "PumpkinPatch":                  ["Hallowed Hollow"],
    "BadassBar":                     ["Badass Crater Bar"],
    "Beatdown":                      ["The Beatdown"],
    "Forge":                         ["The Forge"],
    "IrisCrater":                    ["Badass Crater"],
    "SouthernRaceway":               ["Southern Raceway"],
    "TestingZone":                   ["Digistruct Peak"],
    "EasterTravel":                  ["Wam Bam Island"],
    "Vday":                          ["Rotgut Distillery"],
    "Caves":                         ["Hayter's Folly"],
    "OasisTown":                     ["Oasis"],
    "Refinary":                      ["Washburne Refinery"],
    "SaltFlats":                     ["Wurmwater"],
    "ShipGraveyard":                 ["The Rustyards"],
    "Spire":                         ["Magnys Lighthouse"],
    "TopOfSpire":                    ["Magnys Lighthouse"],
    "HyperionShip":                  ["Terminus"],
    "PowerStation":                  ["Ardorton Station"],
    "RockForest":                    ["Scylla's Grove"],
    "SageCliffs":                    ["Candlerakk's Cragg"],
    "Underground":                   ["Hunter's Grotto"],
    "Underground_Lodge":             ["Hunter's Grotto"],
}

travel_targets = {
    "Helios Station":                     "GD_FastTravelStations.MoonShotIntro",
    "Abandoned Training Facility":        "GD_LevelTravelStations.MoonSlaughterToOutlands",#
    "Cluster 00773 P4ND0R4":              "GD_Ma_FastTravelStations.Ma_LeftCluster_FT",
    "Cluster 99002 0V3RL00K":             "GD_Ma_FastTravelStations.Ma_RightCluster_FT",
    "Concordia":                          "GD_FastTravelStations.Spaceport",
    "Crisis Scar":                        "GD_FastTravelStations.ComFacility",
    "Deck 13 ½":                          "GD_Ma_FastTravelStations.Ma_Deck13_FT",
    "Deck 13.5":                          "GD_Ma_FastTravelStations.Ma_FinalBoss_FT",
    "Eleseer":                            "GD_FastTravelStations.MoonCore",
    "Eye of Helios":                      "GD_FastTravelStations.LaserBoss",
    "Hyperion Hub of Heroism":            "GD_FastTravelStations.Zone_3.CentralTerminal",
    "Jack's Office":                      "GD_FastTravelStations.Zone_3.JacksOffice",
    "Lunar Launching Station":            "GD_FastTravelStations.Laser",
    "Motherlessboard":                    "GD_Ma_LevelTravelStations.MotherboardToDeck13",
    "Outfall Pumping Station":            "GD_LevelTravelStations.Rk5arena_To_Digsite",
    "Outlands Canyon":                    "GD_FastTravelStations.Outlands2",
    "Outlands Spur":                      "GD_FastTravelStations.Outlands",
    "Pity's Fall":                        "GD_FastTravelStations.WreckCrater",
    "Regolith Range":                     "GD_LevelTravelStations.DeadsurfaceToMoonsurface",
    "Research and Development":           "GD_FastTravelStations.RandDFacility",
    "Serenity's Waste":                   "GD_FastTravelStations.Airstrip",
    "Stanton's Liver":                    "GD_FastTravelStations.StantonsLiver_P",
    "Sub-Level 13":                       "GD_LevelTravelStations.Sublevel13ToFactory",
    "Subconscious":                       "GD_Ma_FastTravelStations.Ma_Sub_FT",
    "The Cortex":                         "GD_Ma_LevelTravelStations.SubToSubBoss",
    "The Holodome":                       "GD_Pet_FastTravelStations.EridianSlaughter",
    "The Meriff's Office":                "GD_LevelTravelStations.SpaceportToMeriff",
    "The Nexus":                          "GD_Ma_FastTravelStations.Ma_Nexus_FT",
    "Titan Industrial Facility":          "GD_FastTravelStations.DahlFactory",
    "Titan Robot Production Plant":       "GD_FastTravelStations.DahlFactoryBossStart",
    "Triton Flats":                       "GD_FastTravelStations.MoonCore",
    "Tycho's Ribs":                       "GD_FastTravelStations.AccessShaft", 
    "Veins of Helios":                    "GD_LevelTravelStations.Zone_3.InnerHullToCentralTerminal",
    "Vorago Solitude":                    "GD_FastTravelStations.DigSite",
    # "TODO": "GD_FastTravelStations.AccessShaft",
    # "TODO": "GD_FastTravelStations.Airstrip",
    # "TODO": "GD_FastTravelStations.CoreVault",
    # "TODO": "GD_FastTravelStations.DahlFactoryBoss",
    # "TODO": "GD_FastTravelStations.11BElevator",## crash
    # "TODO": "GD_FastTravelStations.Elevator", ##crash
    # "TODO": "GD_FastTravelStations.ElevatorRide", ##crash
    # "TODO": "GD_FastTravelStations.MoonshotFT",
    # "TODO": "GD_FastTravelStations.MoonshotIntroFT", #crashh
    # "TODO": "GD_FastTravelStations.RnD", #crash
    # "TODO": "GD_Ma_FastTravelStations.Ma_LeftCluster_1way_FT",
    # "TODO": "GD_Ma_FastTravelStations.MA_SubSub_FT",
    
    
    #Bl2
     "Windshear Waste":                    "GD_FastTravelStations.Zone1.GlacialIgloo",
     "Arid Nexus Boneyard":                "GD_FastTravelStations.Zone3.OnFireStone",
     "The Holy Spirits":                   "GD_LevelTravelStations.Zone2.LuckysToGrass",
     "Southpaw Steam & Power":             "GD_FastTravelStations.Zone1.SouthpawFactory",
     "Sanctuary Hole":                     "GD_LevelTravelStations.Zone1.SanctuaryHoleToIce",
     "Hero's Pass":                        "GD_FastTravelStations.Zone3.FinalBossAscent",
     "Bloodshot Stronghold":               "GD_FastTravelStations.Zone1.GoshDam",
     "Three Horns Valley":                 "GD_FastTravelStations.Zone1.IceWest",
     "Sanctuary":                          "GD_FastTravelStations.Sanctuary.Sanctuary",
     "Thousand Cuts":                      "GD_FastTravelStations.Zone2.Cliffs",
     "End of the Line":                    "GD_LevelTravelStations.WilhelmToTundraExpress",
     "Wildlife Exploitation Preserve":     "GD_FastTravelStations.Zone2.PandoraPark",
     "Terramorphous Peak":                 "GD_LevelTravelStations.Zone2.ThresherRaidToCliffs",
     "Tundra Express":                     "GD_FastTravelStations.Zone1.TundraExpress",
     "The Fridge":                         "GD_FastTravelStations.Zone2.TheFridge",
     "Fink's Slaughterhouse":              "GD_LevelTravelStations.Zone2.BanditSlaughterToFridge",
     "Southern Shelf Bay":                 "GD_LevelTravelStations.Zone1.CoveToWaterfront",
     "Frostburn Canyon":                   "GD_FastTravelStations.Zone1.IceCanyon",
     "Three Horns Divide":                 "GD_FastTravelStations.Zone1.IceEast",
     "Highlands":                          "GD_FastTravelStations.Zone2.Grass_A",
     "Natural Selection Annex":            "GD_LevelTravelStations.Zone2.CreatureSlaughterToPandoraPark",
     "The Dust":                           "GD_FastTravelStations.Interlude.Interlude",
     "Friendship Gulag":                   "GD_LevelTravelStations.Interlude.HypInterToInterlude",
     "Opportunity":                        "GD_FastTravelStations.Zone2.HyperionCity",
     "Bloodshot Ramparts":                 "GD_LevelTravelStations.Zone1.DamTopToDam",
     "Arid Nexus Badlands":                "GD_FastTravelStations.FyrestoneOneWay",
     "Southern Shelf":                     "GD_LevelTravelStations.Zone1.WaterfrontToGlacial",
     "Highlands Outwash":                  "GD_FastTravelStations.Outwash",
     "Caustic Caverns":                    "GD_FastTravelStations.Zone1.Caverns",
     "Lynchwood":                          "GD_FastTravelStations.Interlude.Lynchwood",
     "Sawtooth Cauldron":                  "GD_FastTravelStations.Zone3.CraterLake",
     "Ore Chasm":                          "GD_LevelTravelStations.Zone3.RobotSlaughterToAsh",
     "The Bunker":                         "GD_FastTravelStations.Zone2.Cliffs_Boss",
     "Control Core Angel":                 "GD_LevelTravelStations.Zone2.VOGsChamberToBossCliffs",
     "Vault of the Warrior":               "GD_LevelTravelStations.Zone3.VolcanoToFinalBossAscent",
     "Eridium Blight":                     "GD_FastTravelStations.Zone3.Ash",
     "Gluttony Gulch":                     "GD_Allium_FastTravel.Hunger",
     "Marcus's Mercenary Shop":            "GD_Allium_FastTravel.Xmas",
     "Helios Fallen":                      "GD_Anemone_FastTravel.FastTravelStations.Helios",
     "FFS Boss Fight":                     "GD_Anemone_LevelTravel.SanctuaryToResearchCenter",
     "The Backburner":                     "GD_Anemone_FastTravel.FastTravelStations.BackBurner",
     "FFS Intro Sanctuary":                "GD_Anemone_FastTravel.SanctuaryIntro",
     "Dahl Abandon":                       "GD_Anemone_FastTravel.FastTravelStations.OldDust",
     "Mt. Scarab Research Center":         "GD_Anemone_FastTravel.FastTravelStations.ResearchCenter",
     "The Burrows":                        "GD_Anemone_FastTravel.Sandworm_OneWay",
     "Writhing Deep":                      "GD_Anemone_LevelTravel.RaidBossToSandwormCavern",
     "The Forest":                         "GD_Aster_FastTravel.DarkForest",
     "Immortal Woods":                     "GD_Aster_FastTravel.DeadForest",
     "Dragon Keep":                        "GD_Aster_FastTravel.CastleKeep",
     "Unassuming Docks":                   "GD_Aster_FastTravel.Docks",
     "Flamerock Refuge":                   "GD_Aster_FastTravel.Village",
     "Hatred's Shadow":                    "GD_Aster_FastTravel.CastleExterior",
     "Lair of Infinite Agony":             "GD_Aster_FastTravel.Dungeons",
     "Murderlin's Temple":                 "GD_Aster_LevelTravel.TempleOfSlaughterToVillage",
     "Mines of Avarice":                   "GD_Aster_FastTravel.Mines",
     "The Winged Storm":                   "GD_Aster_LevelTravel.DungeonRaidToDungeon",
     "Hallowed Hollow":                    "GD_Flax_FastTravel.PumpkinPatch",
     "Torgue Arena":                       "GD_Iris_LevelTravelStations.Dogleg1.ArenaToCrater",
     "Torgue Arena TAS":                   "GD_Iris_LevelTravelStations.Dogleg1.ArenaTASToCrater", # special case
     "Torgue Arena Ring":                  "GD_Iris_LevelTravelStations.Dogleg1.BackdoorToCrater", # special case
     "The Beatdown":                       "GD_Iris_FastTravelStations.Beatdown",
     "The Forge":                          "GD_Iris_FastTravelStations.Forge",
     "Badass Crater":                      "GD_Iris_FastTravelStations.Hub.IrisCrater",
     "Southern Raceway":                   "GD_Iris_FastTravelStations.SouthernRaceway",
     "Pyro Pete's Bar":                    "GD_Iris_LevelTravelStations.PyroPetesToBeatdown",
     "Badass Crater Bar":                  "GD_Iris_FastTravelStations.BadassBar",
     "Digistruct Peak":                    "GD_Lobelia_FastTravel.TestingZone",
     "Wam Bam Island":                     "GD_Nasturtium_FastTravel.EasterTravel",
     "Rotgut Distillery":                  "GD_Nasturtium_FastTravel.Vday",
     "The Leviathan's Lair":               "GD_Orchid_LevelTravel.WormBelly.WormBellyToSaltFlats",
     "Washburne Refinery":                 "GD_Orchid_FastTravel.Refinary",
     "Wurmwater":                          "GD_Orchid_FastTravel.SaltFlats.SaltFlats",
     "Magnys Lighthouse":                  "GD_Orchid_FastTravel.Spire",
     "The Rustyards":                      "GD_Orchid_FastTravel.ShipGraveyard",
     "Hayter's Folly":                     "GD_Orchid_FastTravel.Caves",
     "Oasis":                              "GD_Orchid_FastTravel.OasisTown.OasisTown",
     "Ardorton Station":                   "GD_Sage_FastTravel.PowerStation",
     "Hunter's Grotto":                    "GD_Sage_FastTravel.Underground",
     "Candlerakk's Cragg":                 "GD_Sage_FastTravel.SageCliffs",
     "Terminus":                           "GD_Sage_LevelTravel.Sage_Travel_ShipToCliffs",
     "Scylla's Grove":                     "GD_Sage_FastTravel.RockForest",
}

region_translation_dict = {
    "intro":                           "Helios Station",
    "heliosstation":                   "Helios Station",
    "abandonedtrainingfacility":       "Abandoned Training Facility",
    "trainingfacility":                "Abandoned Training Facility",
    "cluster00773p4nd0r4":             "Cluster 00773 P4ND0R4",
    "pandorasimulation":               "Cluster 00773 P4ND0R4",
    "cluster990020v3rl00k":            "Cluster 99002 0V3RL00K",
    "overlooksimulation":              "Cluster 99002 0V3RL00K",
    "concordia":                       "Concordia",
    "crisisscar":                      "Crisis Scar",
    "deck13":                          "Deck 13 ½",
    "fakedeck13":                      "Deck 13.5",
    "eleseer":                         "Eleseer",
    "eyeofhelios":                     "Eye of Helios",
    "hyperionhubofheroism":            "Hyperion Hub of Heroism",
    "hubofheroism":                    "Hyperion Hub of Heroism",
    "jacksoffice":                     "Jack's Office",
    "lunarlaunchingstation":           "Lunar Launching Station",
    "motherlessboard":                 "Motherlessboard",
    "outfallpumpingstation":           "Outfall Pumping Station",
    "outlandscanyon":                  "Outlands Canyon",
    "outlandsspur":                    "Outlands Spur",
    "pitysfall":                       "Pity's Fall",
    "drakensburg":                     "Pity's Fall",
    "regolith":                        "Regolith Range",
    "regolithrange":                   "Regolith Range",
    "researchanddevelopment":          "Research and Development",
    "rnd":                             "Research and Development",
    "serenityswaste":                  "Serenity's Waste",
    "serenity":                        "Serenity's Waste",
    "stantonsliver":                   "Stanton's Liver",
    "stanton":                         "Stanton's Liver",
    "sublevel13":                      "Sub-Level 13",
    "subconscious":                    "Subconscious",
    "thecortex":                       "The Cortex",
    "cortex":                          "The Cortex",
    "theholodome":                     "The Holodome",
    "holodome":                        "The Holodome",
    "themeriffsoffice":                "The Meriff's Office",
    "meriffsoffice":                   "The Meriff's Office",
    "thenexus":                        "The Nexus",
    "nexus":                           "The Nexus",
    "titanindustrialfacility":         "Titan Industrial Facility",
    "titanrobotproductionplant":       "Titan Robot Production Plant",
    "titanrobotplant":                 "Titan Robot Production Plant",
    "tritonflats":                     "Triton Flats",
    "tychosribs":                      "Tycho's Ribs",
    "tychoribs":                       "Tycho's Ribs",
    "veinsofhelios":                   "Veins of Helios",
    "voragosolitude":                  "Vorago Solitude",
    
}

progressive_travel_lookup = {
    "basegame": [
        "Helios Station", # index 0 always available
        "Abandoned Training Facility",
        "Concordia",
        "Crisis Scar",
        "Eleseer",
        "Eye of Helios",
        "Hyperion Hub of Heroism",
        "Jack's Office",
        "Lunar Launching Station",
        "Outfall Pumping Station",
        "Outlands Canyon",
        "Outlands Spur",
        "Pity's Fall",
        "Regolith Range",
        "Research and Development",
        "Serenity's Waste",
        "Stanton's Liver",
        "The Holodome",
        "The Meriff's Office",
        "Titan Industrial Facility",
        "Titan Robot Production Plant",
        "Triton Flats",
        "Tycho's Ribs",
        "Veins of Helios",
        "Vorago Solitude",
    ],
    "basegame_side": [
        "",
        "Sub-Level 13", # TODO
        "Southpaw Steam & Power",
        "Fink's Slaughterhouse",
        "The Holy Spirits",
        "Sanctuary Hole",
        "Caustic Caverns",
        "Natural Selection Annex",
        "Lynchwood",
        "Ore Chasm",
        "Terramorphous Peak",
    ],
    "claptrap": [
        "",
        "Cluster 00773 P4ND0R4",
        "Cluster 99002 0V3RL00K",
        "Deck 13 ½",
        "Deck 13.5",
        "Motherlessboard",
        "Subconscious",
        "The Cortex",
        "The Nexus",
    ],
    "shock_drop": [
        "",
        "Abandoned Training Facility",
    ],
    "holodome": [
        "",
        "The Holodome",
    ],
}

progressive_travel_items = {
    "basegame": "Progressive Travel: Base Game",
    "basegame_side": "Progressive Travel: Side Area",
    "holodome": "Progressive Travel: The Holodome Onslaught DLC",
    "shock_drop": "Progressive Travel: Shock Drop Slaughter Pit DLC",
    "claptrap": "Progressive Travel: Claptastic Voyage DLC"
}
progressive_travel_groups = {v: k for k, v in progressive_travel_items.items()}
