vault_symbol_pathname_to_name = {
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":               "Symbol Sanctuary: Rooftop",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":               "Symbol Sanctuary: Moxxi's Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":               "Symbol Sanctuary: Trash Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":             "Symbol Sanctuary: Tire Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":              "Symbol Sanctuary: Parkour Door",

    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol Sanctuary: Rooftop",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                  "Symbol Sanctuary: Moxxi's Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                  "Symbol Sanctuary: Trash Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":                "Symbol Sanctuary: Tire Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":                 "Symbol Sanctuary: Parkour Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                        "Symbol EridiumBlight: Hellsfont Crate",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                        "Symbol EridiumBlight: Stairs Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_518":                      "Symbol EridiumBlight: Refund Building",
    "BanditSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":           "Symbol Fink's: Column",
    "Boss_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol Bunker: Backside",
    "Boss_Volcano_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol VaultOfTheWarrior: Elevator Bottom",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":                     "Symbol SouthernShelfBay: Blackburn Cove Corner",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_235":                     "Symbol SouthernShelfBay: Ice Flows Shipwreck",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_27":                "Symbol Sawtooth: Refinery Container",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":                 "Symbol Sawtooth: Elevator",
    "CreatureSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol NaturalSelectionAnnex: Crate Ceiling",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":            "Symbol HerosPass: Strut",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":            "Symbol HerosPass: Spawn",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_89":                    "Symbol Fridge: Secret Stash",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                    "Symbol Fridge: Sheetmetal Roof",
    "Frost_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":                "Symbol ThreeHornsValley: Slums Wall",           #A Dam Fine Rescue mission
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_31":                     "Symbol ThreeHornsValley: Frostsprings Wall",
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                      "Symbol ThreeHornsValley: Frostsprings Shack",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol AridNexusBoneyard: Pipe",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                  "Symbol AridNexusBoneyard: Turret South of Spawn",
    "Glacial_P.TheWorld:PersistentLevel.WillowInteractiveObject_214":                  "Symbol WindshearWaste: Claptrap's Closet",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_174":             "Symbol ThousandCuts: Buzzard Factory",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_302":             "Symbol ThousandCuts: No Man's Land Shack",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_298":          "Symbol Lynchwood: Gunslinger Roof",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_601":          "Symbol Lynchwood: Main Street",
    "Grass_P.TheWorld:PersistentLevel.WillowInteractiveObject_346":                    "Symbol Highlands: Highlands Tower",
    "HypInterlude_P.TheWorld:PersistentLevel.WillowInteractiveObject_12":              "Symbol FriendshipGulag: Gulag Container",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":             "Symbol Opportunity: Construction Site",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol Opportunity: Office Bridge",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_238":                      "Symbol ThreeHornsDivide: Drydocks Corner",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                        "Symbol ThreeHornsDivide: Billboard",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_79":                       "Symbol ThreeHornsDivide: Windbreak Wall",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_26":           "Symbol Dust: Speedway Wall",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_4":            "Symbol Dust: Buzzard Pad",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":            "Symbol Dust: Moonshiner Lid",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_641":                  "Symbol CausticCaverns: Gravestone Feature",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_89":                   "Symbol CausticCaverns: Bloody Ladder",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_137":                      "Symbol BloodshotStronghold: Pizza Intercom",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_138":                      "Symbol BloodshotStronghold: Switch Room",
    "damtop_p.TheWorld:PersistentLevel.WillowInteractiveObject_0":                     "Symbol BloodshotRamparts: Ramp",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_51":                 "Symbol Frostburn: Blisterpus Cave",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_53":                 "Symbol Frostburn: Ashmouth Pit",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol TorgueArenaRing: Arena Wall",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_772":           "Symbol TorgueArenaRing: Arena Ladder",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Beatdown: Underpass",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_79":            "Symbol Beatdown: School Bus",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_214":           "Symbol Forge: Smack Talker",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Forge: Lava",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_61":            "Symbol Forge: Housing",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":                  "Symbol SouthernRaceway: Zer0 Poster",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_9":                  "Symbol SouthernRaceway: Maya Poster",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_11":            "Symbol BadassCrater: Badass Highway",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_12":            "Symbol BadassCrater: Beatdown Door",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol BadassCrater: Billboard Lower",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_78":            "Symbol BadassCrater: Billboard Upper",
    "Luckys_P.TheWorld:PersistentLevel.WillowInteractiveObject_16":                    "Symbol HolySpirits: Bathroom",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_347":       "Symbol HaytersFolly: Hot Springs Crate",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_461":       "Symbol HaytersFolly: Grendel Exit",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Oasis: Kronus",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_348":   "Symbol Oasis: Lair Exit",       #X Marks the Spot Mission
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_349":   "Symbol Oasis: Lionel Docks",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_367":   "Symbol Oasis: Coral Island",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_496":    "Symbol WashburneRefinery: P3RV-E Lair",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_497":    "Symbol WashburneRefinery: Forge Array",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Wurmwater: Rustyard Corridor",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_400":   "Symbol Wurmwater: Scarlett's Ship",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_401":   "Symbol Wurmwater: The Dish",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_22":      "Symbol Rustyards: Maroonie's Clipper",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_23":      "Symbol Rustyards: Rustyards Fence",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":        "Symbol MagnysLighthouse: House",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_22":        "Symbol MagnysLighthouse: Lighthouse",
    "Orchid_WormBelly_P.TheWorld:PersistentLevel.WillowInteractiveObject_497":         "Symbol LeviathansLair: Lair",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_273":              "Symbol WildlifePreserve: Dockyard Roof",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_274":              "Symbol WildlifePreserve: Broken Boulevard",
    "RobotSlaughter_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_15":      "Symbol OreChasm: Elevator",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_129":        "Symbol CandlerakksCrag: Elite Crossing House",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":         "Symbol CandlerakksCrag: Near Voracidous",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol CandlerakksCrag: Rouge's Lair",
    "Sage_HyperionShip_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol Terminus: Terminus",     #crouch
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":         "Symbol ArdortonStation: Woundspike's Lair",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":          "Symbol ArdortonStation: Psycho Surgery",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":          "Symbol ArdortonStation: Ardo Farm",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":          "Symbol ArdortonStation: Dribble's Lair",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":     "Symbol ScyllasGrove: Low Gut Rut Wall",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_6":      "Symbol ScyllasGrove: Urine Wall",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_8":      "Symbol ScyllasGrove: Upper Village",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_9":      "Symbol ScyllasGrove: Lower Village",
    "Sanctuary_Hole_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":             "Symbol SanctuaryHole: Staircase Wall",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":            "Symbol SouthernShelf: Flynt's Ship",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_397":            "Symbol SouthernShelf: Safehouse",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_398":    "Symbol Southpaw: Before Oney Parkour",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_399":    "Symbol Southpaw: Reeth Area Engine",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_46":     "Symbol Southpaw: Entry Area Ladder",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_116":             "Symbol TerramorphousPeak: Dropdown",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_364":             "Symbol TerramorphousPeak: Elevator",
    "TundraTrain_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol EndOfTheLine: Wilhelm Wall",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol TundraExpress: Fork Shack",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_207":            "Symbol TundraExpress: Facility Roof",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_2":        "Symbol Backburner: Zed's",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_3":        "Symbol Backburner: Entrance",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":             "Symbol HatredsShadow: Sir Boil",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":             "Symbol HatredsShadow: Nefarious Elevator",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_4":             "Symbol HatredsShadow: Sir Mash",
    "CastleKeep_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":           "Symbol DragonKeep: Sacrifice Staircase",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol Forest: Blood Tree Camp",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol Forest: Glenn's Cottage",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol ImmortalWoods: Fields of the Fallen",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_19":         "Symbol ImmortalWoods: Sacred Ruins Upper",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_20":         "Symbol ImmortalWoods: Sacred Ruins Lower",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                      "Symbol UnassumingDocks: Temple Shoreline",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                      "Symbol UnassumingDocks: Forlorn Ruins",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                      "Symbol UnassumingDocks: Hamlet Building",
    "DungeonRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol WingedStorm: The Winged Storm",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_307":                  "Symbol LairOfInfiniteAgony: Platform Corridor",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_308":                  "Symbol LairOfInfiniteAgony: Hall of the Dead",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                   "Symbol LairOfInfiniteAgony: Wailer Drop",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_388":         "Symbol HeliosFallen: Moonshot Complaint Dept",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_446":         "Symbol HeliosFallen: The Freightway",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_447":         "Symbol HeliosFallen: Hellion Hole",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_859":         "Symbol HeliosFallen: Munitions Loading",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_892":         "Symbol HeliosFallen: Fire Control Alpha",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_894":         "Symbol HeliosFallen: The Hold",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":                "Symbol MinesOfAvarice: Ingot Processing",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_16":               "Symbol MinesOfAvarice: Cube Room",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_47":               "Symbol MinesOfAvarice: Greedtooth's Lair",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_187":        "Symbol DahlAbandon: Sinon's Perch Climb",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_269":        "Symbol DahlAbandon: Ride's End",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_36":         "Symbol DahlAbandon: Redclaw Rise Cliff",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_59":         "Symbol DahlAbandon: The Veiny Shaft",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol DahlAbandon: Sinon's Perch Container",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_164": "Symbol MtScarab: Test Candidate Detention",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_167": "Symbol MtScarab: 02 Staircase",
    "ResearchCenter_Research.TheWorld:PersistentLevel.WillowInteractiveObject_737":    "Symbol MtScarab: Experimentation Room",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_68":    "Symbol HuntersGrotto: Arizona's Lair",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_69":    "Symbol HuntersGrotto: Grotto Lodge",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_70":    "Symbol HuntersGrotto: Grotto Start",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":    "Symbol HuntersGrotto: Dahl Door",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1161":           "Symbol WrithingDeep: Elevator Room",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1162":           "Symbol WrithingDeep: Southern Top",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1163":           "Symbol WrithingDeep: Northern Top",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_46":        "Symbol Burrows: Hyperion's Grave",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_60":        "Symbol Burrows: Burrows Cliff",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_1":       "Symbol MurderlinsTemple: The Nursery",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_3":       "Symbol MurderlinsTemple: Below Murderlin",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol FlamerockRefuge: Outskirts",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_383":            "Symbol FlamerockRefuge: Parkour",
}
